@ECHO OFF
Z:
CD \PROGRAMMING\USURPER\SOURCE

ECHO BUILDING EDITOR.EXE
Z:\FPCDOS\BIN\GO32V2\FPC -B -Fueditor -Fu..\..\rmdoor -FE..\bin\i386-go32v2 EDITOR.lpr
IF NOT %ERRORLEVEL% == 0 GOTO END

ECHO BUILDING USURPER.EXE
Z:\FPCDOS\BIN\GO32V2\FPC -B -Fuusurper -Fu..\..\rmdoor -FE..\bin\i386-go32v2 USURPER.lpr
IF NOT %ERRORLEVEL% == 0 GOTO END

:END
PAUSE