{$I DEFINES.INC}
{

Copyright 2007 Jakob Dangarden

 This file is part of Usurper.

    Usurper is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Usurper is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Usurper; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
}
Unit EdMonst2;

Interface

Uses Init, AddMonst;

Procedure Reset_Monsters3;

Implementation

Procedure Reset_Monsters4;
begin

 {**Level 75 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             75,
             'Great Uruk-Hai',
             true,
             false,
             'Filthy scum!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             75,
             'Great Uruk-Hai',
             true,
             false,
             'Filthy scum!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             75,
             'Great Uruk-Hai',
             true,
             false,
             'Filthy scum!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             75,
             'Great Uruk-Hai',
             true,
             false,
             'Filthy scum!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             75,
             'Great Uruk-Hai',
             true,
             false,
             'Filthy scum!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             75,
             'Great Uruk-Hai',
             true,
             false,
             'Filthy scum!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             75,
             'Great Uruk-Hai',
             true,
             false,
             'Filthy scum!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             75,
             'Great Uruk-Hai',
             true,
             false,
             'Filthy scum!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             75,
             'Great Uruk-Hai',
             true,
             false,
             'Filthy scum!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             75,
             'Great Uruk-Hai',
             true,
             false,
             'Filthy scum!');

 {**Level 76 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             76,
             'Future Mercenary',
             true,
             false,
             'Are you nervous?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             76,
             'Future Mercenary',
             true,
             false,
             'Hi there!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             76,
             'Future Mercenary',
             true,
             false,
             'I am here to waste you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             76,
             'Future Mercenary',
             true,
             false,
             'Control the Universe!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             76,
             'Future Mercenary',
             true,
             false,
             'Do you belive in God?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             76,
             'Future Mercenary',
             true,
             false,
             'I must bless you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             76,
             'Future Mercenary',
             true,
             false,
             'Kneel you pagan trash!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             76,
             'Future Mercenary',
             true,false,
             'There is a prize on your head!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             76,
             'Future Mercenary',
             true,
             false,
             'I must kill, I must kill, I must...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             76,
             'Future Mercenary',
             true,
             false,
             'Pain is what you shall recieve!');

 {**Level 77 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             77,
             'Grim Barbarian',
             true,
             false,
             'So, we meet again!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             77,
             'Grim Barbarian',
             true,
             false,
             'Ah...Nay not again!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             77,
             'Grim Barbarian',
             true,
             false,
             'Who sent you? A little snack!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             77,
             'Grim Barbarian',
             true,
             false,
             'Give up now and I will spare you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             77,
             'Dwarf Mercenary',
             true,
             false,
             'Grumf! Trespasser huh!?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             77,
             'Dwarf Mercenary',
             true,
             false,
             'Grr! Here to take my gold huh!?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             77,
             'Halfling Lord',
             true,
             false,
             'Meet my friend WARHAMMER!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             77,
             'Uruk-Hai',
             true,
             false,
             'More blood to spill!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             77,
             'Uruk-Hai',
             true,
             false,
             'You are doomed!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             77,
             'Uruk-Hai',
             true,
             false,
             'Charge!!!!');

 {**Level 78 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             78,
             'Lizard Lord',
             true,
             false,
             'Ssss...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             78,
             'Lizard Lord',
             true,
             false,
             'Ssspeaking of death...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             78,
             'Lizard Lord',
             true,
             false,
             'Learn the way of the Dragon!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             78,
             'Lizard Lord',
             true,
             false,
             'Ssss...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             78,
             'Lizard Lord',
             true,
             false,
             'Mmm...another battle!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             78,
             'Lizard Lord',
             true,
             false,
             'Are you ready for me!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             78,
             'Lizard Lord',
             true,
             false,
             'Tss..Tss..Hoho!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             78,
             'Lizard Lord',
             true,
             false,
             'Let me see...You are flesh!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             78,
             'Lizard Lord',
             true,
             false,
             'Adventurers must die!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             78,
             'Lizard Lord',
             true,
             false,
             'I need food BADLY!');

 {**Level 79 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             79,
             'Dark Vibration',
             true,
             false,
             '...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             79,
             'Dark Vibration',
             true,
             false,
             '...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             79,
             'Dark Vibration',
             true,
             false,
             '...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             79,
             'Dark Vibration',
             true,
             false,
             '...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             79,
             'Dark Vibration',
             true,
             false,
             '...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             79,
             'Dark Vibration',
             true,
             false,
             '...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             79,
             'Dark Vibration',
             true,
             false,
             '...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             79,
             'Dark Vibration',
             true,
             false,
             '...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             79,
             'Dark Vibration',
             true,
             false,
             '...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             79,
             'Dark Vibration',
             true,
             false,
             '...');

 {**Level 80 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             80,
             'Freak Lord',
             true,
             false,
             'Are you Insane?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             80,
             'Freak Lord',
             true,
             false,
             'Are you Sane?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             80,
             'Freak Lord',
             true,
             false,
             'I will help you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             80,
             'Freak Lord',
             true,
             false,
             'Drop your weapons!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             80,
             'Freak Lord',
             true,
             false,
             'Need a friend?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             80,
             'Freak Lord',
             true,
             false,
             'Why so hostile!?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             80,
             'Freak Lord',
             true,
             false,
             'Worship me!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             80,
             'Freak Lord',
             true,
             false,
             'Damn! I have to kill you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             80,
             'Freak Lord',
             true,
             false,
             'Say, where do you come from?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             80,
             'Freak Lord',
             true,
             false,
             'Meet my Spade!');

 {**Level 81 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             81,
             'Monster Mother',
             true,
             false,
             'Oouuuuuuu!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             81,
             'Monster Mother',
             true,
             false,
             'Oouuuuuuu!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             81,
             'Monster Mother',
             true,
             false,
             'Oouuuuuuu!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             81,
             'Monster Mother',
             true,
             false,
             'Oouuuuuuu!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             81,
             'Monster Mother',
             true,
             false,
             'Oouuuuuuu!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             81,
             'Monster Mother',
             true,
             false,
             'Oouuuuuuu!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             81,
             'Monster Mother',
             true,
             false,
             'Oouuuuuuu!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             81,
             'Monster Mother',
             true,
             false,
             'Oouuuuuuu!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             81,
             'Monster Mother',
             true,
             false,
             'Oouuuuuuu!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             81,
             'Monster Mother',
             true,
             false,
             'Oouuuuuuu!');

 {**Level 82 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             82,
             'Troll Mercenary',
             true,
             false,
             'Uruk-Hai!!!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             82,
             'Troll Mercenary',
             true,
             false,
             'Prepare to die Punk!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             82,
             'Uruk-Hai',
             true,
             false,
             'Meet my Axe!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             82,
             'Uruk-Hai',
             true,
             false,
             'I shall keep your head as a souvenir!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             82,
             'Witch King',
             true,
             false,
             'Come closer friend!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             82,
             'Witch King',
             true,
             false,
             'You make me happy!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             82,
             'Witch King',
             true,
             false,
             'Grrrrr...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             82,
             'Orc Chief',
             true,
             false,
             'Charge!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             82,
             'Orc Chief',
             true,
             false,
             'Defend yourself!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             82,
             'Orc Chief',
             true,
             false,
             'Here I come!');

 {**Level 83 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             83,
             'Animated Liquid',
             true,
             false,
             'sssss..sss..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             83,
             'Animated Liquid',
             true,
             false,
             'sssss..sss..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             83,
             'Animated Liquid',
             true,
             false,
             'sssss..sss..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             83,
             'Animated Liquid',
             true,
             false,
             'sssss..sss..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             83,
             'Animated Liquid',
             true,
             false,
             'sssss..sss..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             83,
             'Animated Liquid',
             true,
             false,
             'sssss..sss..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             83,
             'Animated Liquid',
             true,
             false,
             'sssss..sss..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             83,
             'Animated Liquid',
             true,
             false,
             'sssss..sss..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             83,
             'Animated Liquid',
             true,
             false,
             'sssss..sss..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             83,
             'Animated Liquid',
             true,
             false,
             'sssss..sss..');

 {**Level 84 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             84,
             'Purple Monster',
             true,
             false,
             'Wooiii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             84,
             'Purple Monster',
             true,
             false,
             'Wooiii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             84,
             'Purple Monster',
             true,
             false,
             'Wooiii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             84,
             'Purple Monster',
             true,
             false,
             'Wooiii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             84,
             'Purple Monster',
             true,
             false,
             'Wooiii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             84,
             'Purple Monster',
             true,
             false,
             'Wooiii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             84,
             'Purple Monster',
             true,
             false,
             'Wooiii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             84,
             'Purple Monster',
             true,
             false,
             'Wooiii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             84,
             'Purple Monster',
             true,
             false,
             'Wooiii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             84,
             'Purple Monster',
             true,
             false,
             'Wooiii...');

 {**Level 85 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             85,
             'Drug Oriented Beast',
             true,
             false,
             'Hoho...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             85,
             'Drug Oriented Beast',
             true,
             false,
             'Hoho...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             85,
             'Drug Oriented Beast',
             true,
             false,
             'Hoho...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             85,
             'Drug Oriented Beast',
             true,
             false,
             'Hoho...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             85,
             'Drug Oriented Beast',
             true,
             false,
             'Hoho...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             85,
             'Drug Oriented Beast',
             true,
             false,
             'Hoho...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             85,
             'Drug Oriented Beast',
             true,
             false,
             'Hoho...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             85,
             'Drug Oriented Beast',
             true,
             false,
             'Hoho...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             85,
             'Drug Oriented Beast',
             true,
             false,
             'Hoho...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             85,
             'Drug Oriented Beast',
             true,
             false,
             'Hoho...');

 {**Level 86 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             86,
             'Floating Mind',
             true,
             false,
             'Rrrrrr...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             86,
             'Floating Mind',
             true,
             false,
             'Rrrrrr...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             86,
             'Floating Mind',
             true,
             false,
             'Rrrrrr...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             86,
             'Floating Mind',
             true,
             false,
             'Rrrrrr...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             86,
             'Floating Mind',
             true,
             false,
             'Rrrrrr...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             86,
             'Floating Mind',
             true,
             false,
             'Rrrrrr...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             86,
             'Floating Mind',
             true,
             false,
             'Rrrrrr...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             86,
             'Floating Mind',
             true,
             false,
             'Rrrrrr...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             86,
             'Floating Mind',
             true,
             false,
             'Rrrrrr...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             86,
             'Floating Mind',
             true,
             false,
             'Rrrrrr...');

 {**Level 87 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             87,
             'Uncertain Reality',
             true,
             false,
             'Yeeeeee!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             87,
             'Uncertain Reality',
             true,
             false,
             'Yeeeeee!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             87,
             'Uncertain Reality',
             true,
             false,
             'Yeeeeee!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             87,
             'Uncertain Reality',
             true,
             false,
             'Yeeeeee!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             87,
             'Uncertain Reality',
             true,
             false,
             'Yeeeeee!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             87,
             'Uncertain Reality',
             true,
             false,
             'Yeeeeee!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             87,
             'Uncertain Reality',
             true,
             false,
             'Yeeeeee!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             87,
             'Uncertain Reality',
             true,
             false,
             'Yeeeeee!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             87,
             'Uncertain Reality',
             true,
             false,
             'Yeeeeee!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             87,
             'Uncertain Reality',
             true,
             false,
             'Yeeeeee!');

 {**Level 88 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             88,
             'Betrayer',
             true,
             false,
             'I shall put you to sleep!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             88,
             'Betrayer',
             true,
             false,
             'I shall put you to sleep!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             88,
             'Betrayer',
             true,
             false,
             'I shall put you to sleep!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             88,
             'Betrayer',
             true,
             false,
             'I shall put you to sleep!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             88,
             'Betrayer',
             true,
             false,
             'I shall put you to sleep!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             88,
             'Betrayer',
             true,
             false,
             'I shall put you to sleep!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             88,
             'Betrayer',
             true,
             false,
             'I shall put you to sleep!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             88,
             'Betrayer',
             true,
             false,
             'I shall put you to sleep!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             88,
             'Betrayer',
             true,
             false,
             'I shall put you to sleep!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             88,
             'Betrayer',
             true,
             false,
             'I shall put you to sleep!');

 {**Level 89 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             89,
             'Intruder',
             true,
             false,
             'Mmmmmm...Food!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             89,
             'Intruder',
             true,
             false,
             'Mmmmmm...Food!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             89,
             'Intruder',
             true,
             false,
             'Mmmmmm...Food!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             89,
             'Intruder',
             true,
             false,
             'Mmmmmm...Food!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             89,
             'Intruder',
             true,
             false,
             'Mmmmmm...Food!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             89,
             'Intruder',
             true,
             false,
             'Mmmmmm...Food!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             89,
             'Intruder',
             true,
             false,
             'Mmmmmm...Food!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             89,
             'Intruder',
             true,
             false,
             'Mmmmmm...Food!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             89,
             'Intruder',
             true,
             false,
             'Mmmmmm...Food!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             89,
             'Intruder',
             true,
             false,
             'Mmmmmm...Food!');

 {**Level 90 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             90,
             'Eye of Evil',
             true,
             false,
             'I see you DEAD!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             90,
             'Eye of Evil',
             true,
             false,
             'I see you DEAD!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             90,
             'Eye of Evil',
             true,
             false,
             'I see you DEAD!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             90,
             'Eye of Evil',
             true,
             false,
             'I see you DEAD!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             90,
             'Eye of Evil',
             true,
             false,
             'I see you DEAD!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             90,
             'Eye of Evil',
             true,
             false,
             'I see you DEAD!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             90,
             'Eye of Evil',
             true,
             false,
             'I see you DEAD!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             90,
             'Eye of Evil',
             true,
             false,
             'I see you DEAD!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             90,
             'Eye of Evil',
             true,
             false,
             'I see you DEAD!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             90,
             'Eye of Evil',
             true,
             false,
             'I see you DEAD!');

 {**Level 91 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             91,
             'True Antichrist',
             true,
             false,
             'Join me!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             91,
             'True Antichrist',
             true,
             false,
             'Join me!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             91,
             'True Antichrist',
             true,
             false,
             'Join me!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             91,
             'True Antichrist',
             true,
             false,
             'Join me!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             91,
             'True Antichrist',
             true,
             false,
             'Join me!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             91,
             'True Antichrist',
             true,
             false,
             'Join me!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             91,
             'True Antichrist',
             true,
             false,
             'Join me!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             91,
             'True Antichrist',
             true,
             false,
             'Join me!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             91,
             'True Antichrist',
             true,
             false,
             'Join me!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             91,
             'True Antichrist',
             true,
             false,
             'Join me!');

 {**Level 92 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             92,
             'Shadowbeast Overlord',
             true,
             false,
             'I am invincible!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             92,
             'Shadowbeast Overlord',
             true,
             false,
             'I am invincible!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             92,
             'Shadowbeast Overlord',
             true,
             false,
             'I am invincible!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             92,
             'Shadowbeast Overlord',
             true,
             false,
             'I am invincible!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             92,
             'Shadowbeast Overlord',
             true,
             false,
             'I am invincible!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             92,
             'Shadowbeast Overlord',
             true,
             false,
             'I am invincible!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             92,
             'Shadowbeast Overlord',
             true,
             false,
             'I am invincible!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             92,
             'Shadowbeast Overlord',
             true,
             false,
             'I am invincible!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             92,
             'Shadowbeast Overlord',
             true,
             false,
             'I am invincible!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             92,
             'Shadowbeast Overlord',
             true,
             false,
             'I am invincible!');

 {**Level 93 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             93,
             'Lurking Horror',
             true,
             false,
             'Grrr! Grrr! Grrr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             93,
             'Lurking Horror',
             true,
             false,
             'Grrr! Grrr! Grrr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             93,
             'Lurking Horror',
             true,
             false,
             'Grrr! Grrr! Grrr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             93,
             'Lurking Horror',
             true,
             false,
             'Grrr! Grrr! Grrr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             93,
             'Lurking Horror',
             true,
             false,
             'Grrr! Grrr! Grrr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             93,
             'Lurking Horror',
             true,
             false,
             'Grrr! Grrr! Grrr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             93,
             'Lurking Horror',
             true,
             false,
             'Grrr! Grrr! Grrr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             93,
             'Lurking Horror',
             true,
             false,
             'Grrr! Grrr! Grrr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             93,
             'Lurking Horror',
             true,
             false,
             'Grrr! Grrr! Grrr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             93,
             'Lurking Horror',
             true,
             false,
             'Grrr! Grrr! Grrr!');

 {**Level 94 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             94,
             'Salamander from Hell',
             true,
             false,
             'Gnnggg!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             94,
             'Salamander from Hell',
             true,
             false,
             'Gnnggg!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             94,
             'Salamander from Hell',
             true,
             false,
             'Gnnggg!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             94,
             'Salamander from Hell',
             true,
             false,
             'Gnnggg!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             94,
             'Salamander from Hell',
             true,
             false,
             'Gnnggg!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             94,
             'Salamander from Hell',
             true,
             false,
             'Gnnggg!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             94,
             'Salamander from Hell',
             true,
             false,
             'Gnnggg!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             94,
             'Salamander from Hell',
             true,
             false,
             'Gnnggg!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             94,
             'Salamander from Hell',
             true,
             false,
             'Gnnggg!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             94,
             'Salamander from Hell',
             true,
             false,
             'Gnnggg!');

 {**Level 95 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             95,
             'Vulture Lord',
             true,
             false,
             'Waaaa!!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             95,
             'Giant Vulture',
             true,
             false,
             'Waaaa!!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             95,
             'Supreme Vulture',
             true,
             false,
             'Waaaa!!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             95,
             'Red Vulture',
             true,
             false,
             'Waaaa!!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             95,
             'Dragon Vulture',
             true,
             false,
             'Waaaa!!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             95,
             'Saurons Pet',
             true,
             false,
             'Waaaa!!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             95,
             'Mad Vulture',
             true,
             false,
             'Waaaa!!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             95,
             'Dark Vulture',
             true,
             false,
             'Waaaa!!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             95,
             'Black Vulture',
             true,
             false,
             'Waaaa!!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             95,
             'Evil Vulture',
             true,
             false,
             'Waaaa!!');

 {**Level 96 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             96,
             'Shadow Prince',
             true,
             false,
             'Ohh! What have we here!?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             96,
             'Shadow Prince',
             true,
             false,
             'You are to die...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             96,
             'Shadow Prince',
             true,
             false,
             'I have come to rule the world!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             96,
             'Shadow Prince',
             true,
             false,
             'Kneel before your master!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             96,
             'Shadow Prince',
             true,
             false,
             'I like dead adventurers!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             96,
             'Shadow Prince',
             true,
             false,
             'You look like a bag of dirt!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             96,
             'Shadow Prince',
             true,
             false,
             'You do not know of my powers!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             96,
             'Shadow Prince',
             true,
             false,
             'You have choosen the wrong opponent!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             96,
             'Shadow Prince',
             true,
             false,
             'Lick my boots! Serf!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             96,
             'Shadow Prince',
             true,
             false,
             'A nice day for a kill!');

 {**Level 97 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             97,
             'Nameless Horror',
             true,
             false,
             'Ooooooooo...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             97,
             'Nameless Horror',
             true,
             false,
             'Ooooooooo...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             97,
             'Nameless Horror',
             true,
             false,
             'Ooooooooo...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             97,
             'Nameless Horror',
             true,
             false,
             'Ooooooooo...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             97,
             'Nameless Horror',
             true,
             false,
             'Ooooooooo...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             97,
             'Nameless Horror',
             true,
             false,
             'Ooooooooo...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             97,
             'Nameless Horror',
             true,
             false,
             'Ooooooooo...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             97,
             'Nameless Horror',
             true,
             false,
             'Ooooooooo...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             97,
             'Nameless Horror',
             true,
             false,
             'Ooooooooo...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             97,
             'Nameless Horror',
             true,
             false,
             'Ooooooooo...');

 {**Level 98 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             98,
             'Nazgul Lord',
             true,
             false,
             'Feel my wrath!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             98,
             'Nazgul',
             true,
             false,
             'You cannot win this war!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             98,
             'Nazgul',
             true,
             false,
             'Taste my sword!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             98,
             'Nazgul',
             true,
             false,
             'This will be a slaughter!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             98,
             'Nazgul',
             true,
             false,
             'Kiss this world goodbye!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             98,
             'Nazgul',
             true,
             false,
             'Long live Evil!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             98,
             'Nazgul',
             true,
             false,
             'You have not seen the light!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             98,
             'Nazgul',
             true,
             false,
             'Face your defeat! Join us!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             98,
             'Nazgul',
             true,
             false,
             'I hope that you are ready...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             98,
             'Nazgul',
             true,
             false,
             'You against me!? Hahaha!');

 {**Level 99 monsters **}

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             99,
             'Supreme Dragon',
             true,
             false,
             'Mmmm...hoho...!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             99,
             'Dragon Lord',
             true,
             false,
             'Come closer friend!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             99,
             'Mountain Dragon',
             true,
             false,
             'Wanna rip me off huh!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             99,
             'Black Dragon',
             true,
             false,
             'Feel my breath fool!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             99,
             'Screaming Dragon',
             true,
             false,
             'Who are you to challenge ME!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             99,
             'Dark Dragon',
             true,
             false,
             'Ahhh...Another victim!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             99,
             'Evil Dragon',
             true,
             false,
             'Ssssssleeeep!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             99,
             'Dargoths Dragon',
             true,
             false,
             'Grmmmm...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             99,
             'Dragon of Doom',
             true,
             false,
             'I am your destiny!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             99,
             'Ultimate Dragon',
             true,
             false,
             'Watch me!');

 {**Level 100 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             100,
             'Balrog Lord',
             true,
             false,
             'Gnnn...!!!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             100,
             'Balrog Master',
             true,
             false,
             'You have come far!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             100,
             'Giant Balrog',
             true,
             false,
             'Turn back pagan!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             100,
             'Mutant Balrog',
             true,
             false,
             'And I have waited!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             100,
             'Ring Balrog',
             true,
             false,
             'There can only be one!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             100,
             'Supreme Balrog',
             true,
             false,
             'Mmmm...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             100,
             'Hideous Balrog',
             true,
             false,
             'Grrr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             100,
             'Hells Balrog',
             true,
             false,
             'Are you afraid? You should be...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             100,
             'Black Balrog',
             true,
             false,
             'I am disappointed! You look like a little insect!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             100,
             'Balrog of Doom',
             true,
             false,
             'You look like something that just wants to be killed!');

 {**Level 101 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             150,
             'Supreme Being',
             true,
             false,'...');

end;

procedure Reset_Monsters3;
begin

 {**Level 50 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             50,
             'Creeping Death',
             true,
             false,
             'Ohhhii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             50,
             'Creeping Death',
             true,
             false,
             'Ohhhii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             50,
             'Creeping Death',
             true,
             false,
             'Ohhhii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             50,
             'Creeping Death',
             true,
             false,
             'Ohhhii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             50,
             'Creeping Death',
             true,
             false,
             'Ohhhii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             50,
             'Creeping Death',
             true,
             false,
             'Ohhhii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             50,
             'Creeping Death',
             true,
             false,
             'Ohhhii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             50,
             'Creeping Death',
             true,
             false,
             'Ohhhii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             50,
             'Creeping Death',
             true,
             false,
             'Ohhhii...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             50,
             'Creeping Death',
             true,
             false,
             'Ohhhii...');

 {**Level 51 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             51,
             'Murdering Beast',
             true,
             false,
             'Grunt..Grunt..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             51,
             'Murdering Beast',
             true,
             false,
             'Grunt..Grunt..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             51,
             'Murdering Beast',
             true,
             false,
             'Grunt..Grunt..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             51,
             'Murdering Beast',
             true,
             false,
             'Grunt..Grunt..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             51,
             'Murdering Beast',
             true,
             false,
             'Grunt..Grunt..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             51,
             'Murdering Beast',
             true,
             false,
             'Grunt..Grunt..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             51,
             'Murdering Beast',
             true,
             false,
             'Grunt..Grunt..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             51,
             'Murdering Beast',
             true,
             false,
             'Grunt..Grunt..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             51,
             'Murdering Beast',
             true,
             false,
             'Grunt..Grunt..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             51,
             'Murdering Beast',
             true,
             false,
             'Grunt..Grunt..');

 {**Level 52 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             52,
             'Big Bad Wolf',
             true,
             false,
             'Hehe..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             52,
             'Big Bad Wolf',
             true,
             false,
             'Hehe..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             52,
             'Big Bad Wolf',
             true,
             false,
             'Hehe..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             52,
             'Big Bad Wolf',
             true,
             false,
             'Hehe..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             52,
             'Big Bad Wolf',
             true,
             false,
             'Hehe..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             52,
             'Big Bad Wolf',
             true,
             false,
             'Hehe..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             52,
             'Big Bad Wolf',
             true,
             false,
             'Hehe..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             52,
             'Big Bad Wolf',
             true,
             false,
             'Hehe..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             52,
             'Big Bad Wolf',
             true,
             false,
             'Hehe..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             52,
             'Big Bad Wolf',
             true,
             false,
             'Hehe..');

 {**Level 53 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             53,
             'Well Monster',
             true,
             false,
             'Psss..');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             53,
             'Well Monster',
             true,
             false,
             'Psss..');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             53,
             'Well Monster',
             true,
             false,
             'Psss..');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             53,
             'Well Monster',
             true,
             false,
             'Psss..');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             53,
             'Well Monster',
             true,
             false,
             'Psss..');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             53,
             'Well Monster',
             true,
             false,
             'Psss..');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             53,
             'Well Monster',
             true,
             false,
             'Psss..');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             53,
             'Well Monster',
             true,
             false,
             'Psss..');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             53,
             'Well Monster',
             true,
             false,
             'Psss..');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             53,
             'Well Monster',
             true,
             false,
             'Psss..');

 {**Level 54 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             54,
             'Troll Wizard',
             true,
             false,
             'Grouu!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             54,
             'Troll Wizard',
             true,
             false,
             'Grouu!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             54,
             'Troll Wizard',
             true,
             false,
             'Grouu!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             54,
             'Troll Wizard',
             true,
             false,
             'Grouu!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             54,
             'Troll Wizard',
             true,
             false,
             'Grouu!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             54,
             'Troll Wizard',
             true,
             false,
             'Grouu!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             54,
             'Troll Wizard',
             true,
             false,
             'Grouu!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             54,
             'Troll Wizard',
             true,
             false,
             'Grouu!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             54,
             'Troll Wizard',
             true,
             false,
             'Grouu!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             54,
             'Troll Wizard',
             true,
             false,
             'Grouu!');

 {**Level 55 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             55,
             'Physical Nightmare',
             true,
             false,
             'Zzzzzz...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             55,
             'Physical Nightmare',
             true,
             false,
             'Zzzzzz...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             55,
             'Physical Nightmare',
             true,
             false,
             'Zzzzzz...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             55,
             'Physical Nightmare',
             true,
             false,
             'Zzzzzz...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             55,
             'Physical Nightmare',
             true,
             false,
             'Zzzzzz...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             55,
             'Physical Nightmare',
             true,
             false,
             'Zzzzzz...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             55,
             'Physical Nightmare',
             true,
             false,
             'Zzzzzz...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             55,
             'Physical Nightmare',
             true,
             false,
             'Zzzzzz...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             55,
             'Physical Nightmare',
             true,
             false,
             'Zzzzzz...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             55,
             'Physical Nightmare',
             true,
             false,
             'Zzzzzz...');

 {**Level 56 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             56,
             'Supreme Assassin',
             true,
             false,
             'I shall deliver you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             56,
             'Supreme Assassin',
             true,
             false,
             'I shall deliver you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             56,
             'Supreme Assassin',
             true,
             false,
             'I shall deliver you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             56,
             'Supreme Assassin',
             true,
             false,
             'I shall deliver you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             56,
             'Supreme Assassin',
             true,
             false,
             'I shall deliver you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             56,
             'Supreme Assassin',
             true,
             false,
             'I shall deliver you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             56,
             'Supreme Assassin',
             true,
             false,
             'I shall deliver you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             56,
             'Supreme Assassin',
             true,
             false,
             'I shall deliver you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             56,
             'Supreme Assassin',
             true,
             false,
             'I shall deliver you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             56,
             'Supreme Assassin',
             true,
             false,
             'I shall deliver you!');

 {**Level 57 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             57,
             'Teacher of Death',
             true,
             false,
             'Another visitor! Stay a while!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             57,
             'Teacher of Death',
             true,
             false,
             'Another visitor! Stay a while!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             57,
             'Teacher of Death',
             true,
             false,
             'Another visitor! Stay a while!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             57,
             'Teacher of Death',
             true,
             false,
             'Another visitor! Stay a while!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             57,
             'Teacher of Death',
             true,
             false,
             'Another visitor! Stay a while!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             57,
             'Teacher of Death',
             true,
             false,
             'Another visitor! Stay a while!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             57,
             'Teacher of Death',
             true,
             false,
             'Another visitor! Stay a while!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             57,
             'Teacher of Death',
             true,
             false,
             'Another visitor! Stay a while!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             57,
             'Teacher of Death',
             true,
             false,
             'Another visitor! Stay a while!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             57,
             'Teacher of Death',
             true,
             false,
             'Another visitor! Stay a while!');

 {**Level 58 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             58,
             'Dominator',
             true,
             false,
             'I need to practice...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             58,
             'Dominator',
             true,
             false,
             'I need to practice...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             58,
             'Dominator',
             true,
             false,
             'I need to practice...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             58,
             'Dominator',
             true,
             false,
             'I need to practice...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             58,
             'Dominator',
             true,
             false,
             'I need to practice...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             58,
             'Dominator',
             true,
             false,
             'I need to practice...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             58,
             'Dominator',
             true,
             false,
             'I need to practice...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             58,
             'Dominator',
             true,
             false,
             'I need to practice...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             58,
             'Dominator',
             true,
             false,
             'I need to practice...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             58,
             'Dominator',
             true,
             false,
             'I need to practice...');

 {**Level 59 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             59,
             'Witchdoctor',
             true,
             false,
             'Asghal Masghal Nizpo Wahr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             59,
             'Witchdoctor',
             true,
             false,
             'Asghal Masghal Nizpo Wahr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             59,
             'Witchdoctor',
             true,
             false,
             'Asghal Masghal Nizpo Wahr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             59,
             'Witchdoctor',
             true,
             false,
             'Asghal Masghal Nizpo Wahr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             59,
             'Witchdoctor',
             true,
             false,
             'Asghal Masghal Nizpo Wahr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             59,
             'Witchdoctor',
             true,
             false,
             'Asghal Masghal Nizpo Wahr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             59,
             'Witchdoctor',
             true,
             false,
             'Asghal Masghal Nizpo Wahr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             59,
             'Witchdoctor',
             true,
             false,
             'Asghal Masghal Nizpo Wahr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             59,
             'Witchdoctor',
             true,
             false,
             'Asghal Masghal Nizpo Wahr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             59,
             'Witchdoctor',
             true,
             false,
             'Asghal Masghal Nizpo Wahr!');

 {**Level 60 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             60,
             'Ghoul Lord',
             true,
             false,
             'The winds are true...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             60,
             'Ghoul Lord',
             true,
             false,
             'The winds are true...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             60,
             'Ghoul Lord',
             true,
             false,
             'The winds are true...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             60,
             'Ghoul Lord',
             true,
             false,
             'The winds are true...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             60,
             'Ghoul Lord',
             true,
             false,
             'The winds are true...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             60,
             'Ghoul Lord',
             true,
             false,
             'The winds are true...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             60,
             'Ghoul Lord',
             true,
             false,
             'The winds are true...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             60,
             'Ghoul Lord',
             true,
             false,
             'The winds are true...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             60,
             'Ghoul Lord',
             true,
             false,
             'The winds are true...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             60,
             'Ghoul Lord',
             true,
             false,
             'The winds are true...');

 {**Level 61 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             61,
             'Red Tiger',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             61,
             'Red Tiger',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             61,
             'Red Tiger',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             61,
             'Red Tiger',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             61,
             'Red Tiger',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             61,
             'Red Tiger',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             61,
             'Red Tiger',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             61,
             'Red Tiger',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             61,
             'Red Tiger',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             61,
             'Red Tiger',
             true,
             false,
             'Grrrrr!');

 {**Level 62 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             62,
             'Berzerk from Hell',
             true,
             false,
             'Run, run while you still can...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             62,
             'Berzerk from Hell',
             true,
             false,
             'Run, run while you still can...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             62,
             'Berzerk from Hell',
             true,
             false,
             'Run, run while you still can...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             62,
             'Berzerk from Hell',
             true,
             false,
             'Run, run while you still can...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             62,
             'Berzerk from Hell',
             true,
             false,
             'Run, run while you still can...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             62,
             'Berzerk from Hell',
             true,
             false,
             'Run, run while you still can...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             62,
             'Berzerk from Hell',
             true,
             false,
             'Run, run while you still can...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             62,
             'Berzerk from Hell',
             true,
             false,
             'Run, run while you still can...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             62,
             'Berzerk from Hell',
             true,
             false,
             'Run, run while you still can...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             62,
             'Berzerk from Hell',
             true,
             false,
             'Run, run while you still can...');

 {**Level 63 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             63,
             'Phantasy Lord',
             true,
             false,
             'You are not worth dealing with!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             63,
             'Phantasy Lord',
             true,
             false,
             'You are not wort dealing with!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             63,
             'Phantasy Lord',
             true,
             false,
             'You are not worth dealing with!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             63,
             'Phantasy Lord',
             true,
             false,
             'You are not worth dealing with!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             63,
             'Phantasy Lord',
             true,
             false,
             'You are not worth dealing with!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             63,
             'Phantasy Lord',
             true,
             false,
             'You are not worth dealing with!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             63,
             'Phantasy Lord',
             true,
             false,
             'You are not worth dealing with!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             63,
             'Phantasy Lord',
             true,
             false,
             'You are not worth dealing with!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             63,
             'Phantasy Lord',
             true,
             false,
             'You are not worth dealing with!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             63,
             'Phantasy Lord',
             true,
             false,
             'You are not worth dealing with!');

 {**Level 64 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             64,
             'Ruthless Mage',
             true,
             false,
             'Hello, dear friend!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             64,
             'Ruthless Mage',
             true,
             false,
             'Hello, dear friend!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             64,
             'Ruthless Mage',
             true,
             false,
             'Hello, dear friend!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             64,
             'Ruthless Mage',
             true,
             false,
             'Hello, dear friend!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             64,
             'Ruthless Mage',
             true,
             false,
             'Hello, dear friend!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             64,
             'Ruthless Mage',
             true,
             false,
             'Hello, dear friend!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             64,
             'Ruthless Mage',
             true,
             false,
             'Hello, dear friend!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             64,
             'Ruthless Mage',
             true,
             false,
             'Hello, dear friend!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             64,
             'Ruthless Mage',
             true,
             false,
             'Hello, dear friend!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             64,
             'Ruthless Mage',
             true,
             false,
             'Hello, dear friend!');

 {**Level 65 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             65,
             'Disturbed Sense',
             true,
             false,
             'Zuuuuhhh...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             65,
             'Disturbed Sense',
             true,
             false,
             'Zuuuuhhh...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             65,
             'Disturbed Sense',
             true,
             false,
             'Zuuuuhhh...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             65,
             'Disturbed Sense',
             true,
             false,
             'Zuuuuhhh...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             65,
             'Disturbed Sense',
             true,
             false,
             'Zuuuuhhh...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             65,
             'Disturbed Sense',
             true,
             false,
             'Zuuuuhhh...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             65,
             'Disturbed Sense',
             true,
             false,
             'Zuuuuhhh...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             65,
             'Disturbed Sense',
             true,
             false,
             'Zuuuuhhh...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             65,
             'Disturbed Sense',
             true,
             false,
             'Zuuuuhhh...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             65,
             'Disturbed Sense',
             true,
             false,
             'Zuuuuhhh...');

 {**Level 66 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             66,
             'Mind Corruptor',
             true,
             false,
             'Ihhhhh..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             66,
             'Mind Corruptor',
             true,
             false,
             'Ihhhhh..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             66,
             'Mind Corruptor',
             true,
             false,
             'Ihhhhh..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             66,
             'Mind Corruptor',
             true,
             false,
             'Ihhhhh..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             66,
             'Mind Corruptor',
             true,
             false,
             'Ihhhhh..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             66,
             'Mind Corruptor',
             true,
             false,
             'Ihhhhh..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             66,
             'Mind Corruptor',
             true,
             false,
             'Ihhhhh..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             66,
             'Mind Corruptor',
             true,
             false,
             'Ihhhhh..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             66,
             'Mind Corruptor',
             true,
             false,
             'Ihhhhh..');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             66,
             'Mind Corruptor',
             true,
             false,
             'Ihhhhh..');

 {**Level 67 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             67,
             'Senior Thug',
             true,
             false,
             'I am your fate!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             67,
             'Senior Thug',
             true,
             false,
             'I am your fate!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             67,
             'Senior Thug',
             true,
             false,
             'I am your fate!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             67,
             'Senior Thug',
             true,
             false,
             'I am your fate!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             67,
             'Senior Thug',
             true,
             false,
             'I am your fate!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             67,
             'Senior Thug',
             true,
             false,
             'I am your fate!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             67,
             'Senior Thug',
             true,
             false,
             'I am your fate!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             67,
             'Senior Thug',
             true,
             false,
             'I am your fate!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             67,
             'Senior Thug',
             true,
             false,
             'I am your fate!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             67,
             'Senior Thug',
             true,
             false,
             'I am your fate!');

 {**Level 68 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             68,
             'Mind Bender',
             true,
             false,
             'Humhumhumhumhum!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             68,
             'Mind Bender',
             true,
             false,
             'Humhumhumhumhum!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             68,
             'Mind Bender',
             true,
             false,
             'Humhumhumhumhum!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             68,
             'Mind Bender',
             true,
             false,
             'Humhumhumhumhum!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             68,
             'Mind Bender',
             true,
             false,
             'Humhumhumhumhum!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             68,
             'Mind Bender',
             true,
             false,
             'Humhumhumhumhum!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             68,
             'Mind Bender',
             true,
             false,
             'Humhumhumhumhum!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             68,
             'Mind Bender',
             true,
             false,
             'Humhumhumhumhum!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             68,
             'Mind Bender',
             true,
             false,
             'Humhumhumhumhum!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             68,
             'Mind Bender',
             true,
             false,
             'Humhumhumhumhum!');

 {**Level 69 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             69,
             'Animated Fear',
             true,
             false,
             'Sssssss...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             69,
             'Animated Fear',
             true,
             false,
             'Sssssss...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             69,
             'Animated Fear',
             true,
             false,
             'Sssssss...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             69,
             'Animated Fear',
             true,
             false,
             'Sssssss...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             69,
             'Animated Fear',
             true,
             false,
             'Sssssss...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             69,
             'Animated Fear',
             true,
             false,
             'Sssssss...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             69,
             'Animated Fear',
             true,
             false,
             'Sssssss...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             69,
             'Animated Fear',
             true,
             false,
             'Sssssss...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             69,
             'Animated Fear',
             true,
             false,
             'Sssssss...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             69,
             'Animated Fear',
             true,
             false,
             'Sssssss...');

 {**Level 70 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             70,
             'Life Distinguisher',
             true,
             false,
             'Oh! Another customer!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             70,
             'Life Distinguisher',
             true,
             false,
             'Oh! Another customer!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             70,
             'Life Distinguisher',
             true,
             false,
             'Oh! Another customer!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             70,
             'Life Distinguisher',
             true,
             false,
             'Oh! Another customer!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             70,
             'Life Distinguisher',
             true,
             false,
             'Oh! Another customer!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             70,
             'Life Distinguisher',
             true,
             false,
             'Oh! Another customer!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             70,
             'Life Distinguisher',
             true,
             false,
             'Oh! Another customer!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             70,
             'Life Distinguisher',
             true,
             false,
             'Oh! Another customer!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             70,
             'Life Distinguisher',
             true,
             false,
             'Oh! Another customer!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             70,
             'Life Distinguisher',
             true,
             false,
             'Oh! Another customer!');

 {**Level 71 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             71,
             'Pain Sequel',
             true,
             false,
             'Gooorgh!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             71,
             'Pain Sequel',
             true,
             false,
             'Gooorgh!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             71,
             'Pain Sequel',
             true,
             false,
             'Gooorgh!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             71,
             'Pain Sequel',
             true,
             false,
             'Gooorgh!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             71,
             'Pain Sequel',
             true,
             false,
             'Gooorgh!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             71,
             'Pain Sequel',
             true,
             false,
             'Gooorgh!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             71,
             'Pain Sequel',
             true,
             false,
             'Gooorgh!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             71,
             'Pain Sequel',
             true,
             false,
             'Gooorgh!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             71,
             'Pain Sequel',
             true,
             false,
             'Gooorgh!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             71,
             'Pain Sequel',
             true,
             false,
             'Gooorgh!');

 {**Level 72 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             72,
             'Blob',
             true,
             false,
             'Momph!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             72,
             'Blob',
             true,
             false,
             'Momph!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             72,
             'Blob',
             true,
             false,
             'Momph!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             72,
             'Blob',
             true,
             false,
             'Momph!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             72,
             'Blob',
             true,
             false,
             'Momph!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             72,
             'Blob',
             true,
             false,
             'Momph!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             72,
             'Blob',
             true,
             false,
             'Momph!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             72,
             'Blob',
             true,
             false,
             'Momph!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             72,
             'Blob',
             true,
             false,
             'Momph!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             72,
             'Blob',
             true,
             false,
             'Momph!?');

 {**Level 73 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             73,
             'Tripper',
             true,
             false,
             'I have just decided to kill You!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             73,
             'Tripper',
             true,
             false,
             'I have just decided to kill You!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             73,
             'Tripper',
             true,
             false,
             'I have just decided to kill You!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             73,
             'Tripper',
             true,
             false,
             'I have just decided to kill You!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             73,
             'Tripper',
             true,
             false,
             'I have just decided to kill You!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             73,
             'Tripper',
             true,
             false,
             'I have just decided to kill You!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             73,
             'Tripper',
             true,
             false,
             'I have just decided to kill You!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             73,
             'Tripper',
             true,
             false,
             'I have just decided to kill You!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             73,
             'Tripper',
             true,
             false,
             'I have just decided to kill You!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             73,
             'Tripper',
             true,
             false,
             'I have just decided to kill You!');

 {**Level 74 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             74,
             'Gongong',
             true,
             false,'...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             74,
             'Gongong',
             true,
             false,'...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             74,
             'Gongong',
             true,
             false,'...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             74,
             'Gongong',
             true,
             false,'...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             74,
             'Gongong',
             true,
             false,'...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             74,
             'Gongong',
             true,
             false,'...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             74,
             'Gongong',
             true,
             false,'...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             74,
             'Gongong',
             true,
             false,'...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             74,
             'Gongong',
             true,
             false,'...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             74,
             'Gongong',
             true,
             false,'...');

 reset_monsters4;

end;
end.
