{$I DEFINES.INC}
{

Copyright 2007 Jakob Dangarden

 This file is part of Usurper.

    Usurper is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Usurper is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Usurper; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
}
Unit EdMonst;

Interface

Procedure Reset_Monsters; {All the Monsters in Usurper}

Implementation

uses file_io, init, addmonst,
     edmonst2; {more monsters are here in edmonst2}

Procedure Reset_Monsters2;
begin

 {**Level 25 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Wandering Ghoul',
             true,
             false,
             'Greetings adventurer...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Wandering Ghoul',
             true,
             false,
             'Greetings adventurer...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Wandering Ghoul',
             true,
             false,
             'Greetings adventurer...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Wandering Ghoul',
             true,
             false,
             'Greetings adventurer...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Wandering Ghoul',
             true,
             false,
             'Greetings adventurer...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Wandering Ghoul',
             true,
             false,
             'Greetings adventurer...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Wandering Ghoul',
             true,
             false,
             'Greetings adventurer...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Wandering Ghoul',
             true,
             false,
             'Greetings adventurer...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Wandering Ghoul',
             true,
             false,
             'Greetings adventurer...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Wandering Ghoul',
             true,
             false,
             'Greetings adventurer...');

 {**Level 26 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             26,
             'Cave Gorilla',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             26,
             'Cave Gorilla',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             26,
             'Cave Gorilla',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             26,
             'Cave Gorilla',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             26,
             'Cave Gorilla',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             26,
             'Cave Gorilla',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             26,
             'Cave Gorilla',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             26,
             'Cave Gorilla',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             26,
             'Cave Gorilla',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             26,
             'Cave Gorilla',
             true,
             false,
             'Grrrrr!');

 {**Level 27 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             27,
             'Troll Master',
             true,
             false,
             'Hehehe...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             27,
             'Troll Master',
             true,
             false,
             'Hehehe...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             27,
             'Troll Master',
             true,
             false,
             'Hehehe...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             27,
             'Troll Master',
             true,
             false,
             'Hehehe...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             27,
             'Troll Master',
             true,
             false,
             'Hehehe...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             27,
             'Troll Master',
             true,
             false,
             'Hehehe...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             27,
             'Troll Master',
             true,
             false,
             'Hehehe...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             27,
             'Troll Master',
             true,
             false,
             'Hehehe...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             27,
             'Troll Master',
             true,
             false,
             'Hehehe...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             27,
             'Troll Master',
             true,
             false,
             'Hehehe...');

 {**Level 28 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             28,
             'Godzilla',
             true,
             false,
             'Uhhh?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             28,
             'Godzilla',
             true,
             false,
             'Uhhh?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             28,
             'Godzilla',
             true,
             false,
             'Uhhh?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             28,
             'Godzilla',
             true,
             false,
             'Uhhh?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             28,
             'Godzilla',
             true,
             false,
             'Uhhh?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             28,
             'Godzilla',
             true,
             false,
             'Uhhh?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             28,
             'Godzilla',
             true,
             false,
             'Uhhh?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             28,
             'Godzilla',
             true,
             false,
             'Uhhh?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             28,
             'Godzilla',
             true,
             false,
             'Uhhh?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             28,
             'Godzilla',
             true,
             false,
             'Uhhh?');

 {**Level 29 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             29,
             'Nocturne',
             true,
             false,
             'Ihhhhhhh!!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             29,
             'Nocturne',
             true,
             false,
             'Ihhhhhhh!!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             29,
             'Nocturne',
             true,
             false,
             'Ihhhhhhh!!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             29,
             'Nocturne',
             true,
             false,
             'Ihhhhhhh!!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             29,
             'Nocturne',
             true,
             false,
             'Ihhhhhhh!!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             29,
             'Nocturne',
             true,
             false,
             'Ihhhhhhh!!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             29,
             'Nocturne',
             true,
             false,
             'Ihhhhhhh!!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             29,
             'Nocturne',
             true,
             false,
             'Ihhhhhhh!!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             29,
             'Nocturne',
             true,
             false,
             'Ihhhhhhh!!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             29,
             'Nocturne',
             true,
             false,
             'Ihhhhhhh!!');

 {**Level 30 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             30,
             'Gargoyle Lord',
             true,
             false,
             'Food! How nice!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             30,
             'Gargoyle Lord',
             true,
             false,
             'Food! How nice!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             30,
             'Gargoyle Lord',
             true,
             false,'Food! How nice!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             30,
             'Gargoyle Lord',
             true,
             false,
             'Food! How nice!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             30,
             'Gargoyle Lord',
             true,
             false,
             'Food! How nice!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             30,
             'Gargoyle Lord',
             true,
             false,
             'Food! How nice!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             30,
             'Gargoyle Lord',
             true,
             false,
             'Food! How nice!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             30,
             'Gargoyle Lord',
             true,
             false,
             'Food! How nice!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             30,
             'Gargoyle Lord',
             true,
             false,
             'Food! How nice!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             30,
             'Gargoyle Lord',
             true,
             false,
             'Food! How nice!');

 {**Level 31 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             31,
             'Veteran Ranger',
             true,
             false,
             'Howdy!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             31,
             'Veteran Ranger',
             true,
             false,
             'Howdy!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             31,
             'Veteran Ranger',
             true,
             false,
             'Howdy!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             31,
             'Veteran Ranger',
             true,
             false,
             'Howdy!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             31,
             'Veteran Ranger',
             true,
             false,
             'Howdy!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             31,
             'Veteran Ranger',
             true,
             false,
             'Howdy!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             31,
             'Veteran Ranger',
             true,
             false,
             'Howdy!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             31,
             'Veteran Ranger',
             true,
             false,
             'Howdy!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             31,
             'Veteran Ranger',
             true,
             false,
             'Howdy!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             31,
             'Veteran Ranger',
             true,
             false,
             'Howdy!');

 {**Level 32 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             32,
             'Large Troll',
             true,
             false,
             'Ready for pain!?');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             32,
             'Huge Troll',
             true,
             false,
             'Done with your prayers?');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             32,
             'Small Troll',
             true,
             false,
             'Meet my Club!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             32,
             'Medium Troll',
             true,
             false,
             'Charge!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             32,
             'Giant Troll',
             true,
             false,
             'Beg for mercy or meeet your destiny!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             32,
             'Large Troll',
             true,
             false,
             'Aaaaarghhhh!!!!!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             32,
             'Large Troll',
             true,
             false,
             'Prepare for battle!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             32,
             'Large Troll',
             true,
             false,
             'DIE!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             32,
             'Troll',
             true,
             false,
             'Another visitor! Stay a while...stay forver!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             32,
             'Troll',
             true,
             false,
             'I have punks like you for breakfast!');

 {**Level 33 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             33,
             'Gorilla Lord',
             true,
             false,
             'Gruuuuu!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             33,
             'Gorilla Lord',
             true,
             false,
             'Gruuuuu!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             33,
             'Gorilla Lord',
             true,
             false,
             'Gruuuuu!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             33,
             'Gorilla Lord',
             true,
             false,
             'Gruuuuu!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             33,
             'Gorilla Lord',
             true,
             false,
             'Gruuuuu!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             33,
             'Gorilla Lord',
             true,
             false,
             'Gruuuuu!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             33,
             'Gorilla Lord',
             true,
             false,
             'Gruuuuu!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             33,
             'Gorilla Lord',
             true,
             false,
             'Gruuuuu!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             33,
             'Gorilla Lord',
             true,
             false,
             'Gruuuuu!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             33,
             'Gorilla Lord',
             true,
             false,
             'Gruuuuu!?');

 {**Level 34 monsters **}
 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             34,
             'Orc Warlord',
             true,
             false,
             'Haha! You against me! What has the world come to?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             34,
             'Orc Warlord',
             true,
             false,
             'Haha! You against me! What has the world come to ?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             34,
             'Orc Warlord',
             true,
             false,
             'Mmmmm....you will do!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             34,
             'Orc Warlord',
             true,
             false,
             'Battle practice! Ex-slave?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             34,
             'Grinning Ape',
             true,
             false,
             'Tchiii! Tchi! Tchi!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             34,
             'Grinning Ape',
             true,
             false,
             'Tchiii! Tchi! Tchi!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             34,
             'Grinning Ape',
             true,
             false,
             'Tchiii! Tchi! Tchi!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             34,
             'Grinning Ape',
             true,
             false,
             'Tchiii! Tchi! Tchi!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             34,
             'Grinning Ape',
             true,
             false,
             'Tchiii! Tchi! Tchi!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             34,
             'Grinning Ape',
             true,
             false,
             'Tchiii! Tchi! Tchi!');

 {**Level 35 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Nameless Fear',
             true,
             false,
             'Zzzzzzzzzzz...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Nameless Fear',
             true,
             false,
             'Zzzzzzzzzzz...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Nameless Fear',
             true,
             false,
             'Zzzzzzzzzzz...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Nameless Fear',
             true,
             false,
             'Zzzzzzzzzzz...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Nameless Fear',
             true,
             false,
             'Zzzzzzzzzzz...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Nameless Fear',
             true,
             false,
             'Zzzzzzzzzzz...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Nameless Fear',
             true,
             false,
             'Zzzzzzzzzzz...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Nameless Fear',
             true,
             false,
             'Zzzzzzzzzzz...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Nameless Fear',
             true,
             false,
             'Zzzzzzzzzzz...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Nameless Fear',
             true,
             false,
             'Zzzzzzzzzzz...');

 {**Level 36 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             36,
             'Blood Guardian',
             true,
             false,
             'Go away!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             36,
             'Blood Guardian',
             true,
             false,
             'Go away!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             36,
             'Blood Guardian',
             true,
             false,
             'Go away!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             36,
             'Blood Guardian',
             true,
             false,
             'Go away!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             36,
             'Blood Guardian',
             true,
             false,
             'Buzz Off!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             36,
             'Blood Guardian',
             true,
             false,
             'Buzz Off!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             36,
             'Blood Guardian',
             true,
             false,
             'Buzz Off!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             36,
             'Blood Guardian',
             true,
             false,
             'Buzz Off!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             36,
             'Blood Guardian',
             true,
             false,
             'Buzz Off!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             36,
             'Blood Guardian',
             true,
             false,
             'Get lost!');

 {**Level 37 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             37,
             'Creeping Fear',
             true,
             false,
             'Food! Food! Food!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             37,
             'Creeping Fear',
             true,
             false,
             'Food! Food! Food!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             37,
             'Creeping Fear',
             true,
             false,
             'Food! Food! Food!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             37,
             'Creeping Fear',
             true,
             false,
             'Food! Food! Food!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             37,
             'Creeping Fear',
             true,
             false,
             'Kill! Kill! Kill!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             37,
             'Creeping Fear',
             true,
             false,
             'Kill! Kill! Kill!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             37,
             'Creeping Fear',
             true,
             false,
             'Kill! Kill! Kill!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             37,
             'Creeping Fear',
             true,
             false,
             'Kill! Kill! Kill!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             37,
             'Creeping Fear',
             true,
             false,
             'Kill! Kill! Kill!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             37,
             'Creeping Fear',
             true,
             false,
             'Kill! Kill! Kill!');

 {**Level 38 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             38,
             'Cat Woman',
             true,
             false,
             'A great day for battle!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             38,
             'Cat Woman',
             true,
             false,
             'A great day for battle!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             38,
             'Cat Woman',
             true,
             false,
             'A great day for battle!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             38,
             'Cat Woman',
             true,
             false,
             'A great day for battle!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             38,
             'Cat Woman',
             true,
             false,
             'A great day for battle!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             38,
             'Cat Woman',
             true,
             false,
             'A great day for battle!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             38,
             'Cat Woman',
             true,
             false,
             'A great day for battle!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             38,
             'Cat Woman',
             true,
             false,
             'A great day for battle!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             38,
             'Cat Woman',
             true,
             false,
             'A great day for battle!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             38,
             'Cat Woman',
             true,
             false,
             'A great day for battle!');

 {**Level 39 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             39,
             'Dark Witch',
             true,
             false,
             'Sccchaaaa!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             39,
             'Dark Witch',
             true,
             false,
             'Sccchaaaa!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             39,
             'Dark Witch',
             true,
             false,
             'Sccchaaaa!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             39,
             'Dark Witch',
             true,
             false,
             'Sccchaaaa!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             39,
             'Dark Witch',
             true,
             false,
             'Sccchaaaa!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             39,
             'Dark Witch',
             true,
             false,
             'Sccchaaaa!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             39,
             'Dark Witch',
             true,
             false,
             'Sccchaaaa!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             39,
             'Dark Witch',
             true,
             false,
             'Sccchaaaa!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             39,
             'Dark Witch',
             true,
             false,
             'Sccchaaaa!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             39,
             'Dark Witch',
             true,
             false,
             'Sccchaaaa!');

 {**Level 40 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             40,
             'Shadow Lord',
             true,
             false,
             'You made a mistake coming down here...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             40,
             'Shadow Lord',
             true,
             false,
             'You made a mistake coming down here...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             40,
             'Shadow Lord',
             true,
             false,
             'You made a mistake coming down here...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             40,
             'Shadow Lord',
             true,
             false,
             'You made a mistake coming down here...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             40,
             'Shadow Lord',
             true,
             false,
             'You made a mistake coming down here...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             40,
             'Shadow Lord',
             true,
             false,
             'You made a mistake coming down here...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             40,
             'Shadow Lord',
             true,
             false,
             'You made a mistake coming down here...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             40,
             'Shadow Lord',
             true,
             false,
             'You made a mistake coming down here...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             40,
             'Shadow Lord',
             true,
             false,
             'You made a mistake coming down here...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             40,
             'Shadow Lord',
             true,
             false,
             'You made a mistake coming down here...');

 {**Level 41 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             41,
             'War Veteran',
             true,
             false,
             'Show me what you got!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             41,
             'War Veteran',
             true,
             false,
             'Show me what you got!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             41,
             'War Veteran',
             true,
             false,
             'Show me what you got!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             41,
             'War Veteran',
             true,
             false,
             'Show me what you got!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             41,
             'War Veteran',
             true,
             false,
             'Show me what you got!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             41,
             'War Veteran',
             true,
             false,
             'Show me what you got!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             41,
             'War Veteran',
             true,
             false,
             'Show me what you got!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             41,
             'War Veteran',
             true,
             false,
             'Show me what you got!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             41,
             'War Veteran',
             true,
             false,
             'Show me what you got!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             41,
             'War Veteran',
             true,
             false,
             'Show me what you got!');

 {**Level 42 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             42,
             'Monster Shadow',
             true,
             false,
             'I...wa...yo..he...mis....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             42,
             'Monster Shadow',
             true,
             false,
             'I...wa...yo..he...mis....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             42,
             'Monster Shadow',
             true,
             false,
             'I...wa...yo..he...mis....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             42,
             'Monster Shadow',
             true,
             false,
             'I...wa...yo..he...mis....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             42,
             'Monster Shadow',
             true,
             false,
             'I...wa...yo..he...mis....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             42,
             'Monster Shadow',
             true,
             false,
             'I...wa...yo..he...mis....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             42,
             'Monster Shadow',
             true,
             false,
             'I...wa...yo..he...mis....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             42,
             'Monster Shadow',
             true,
             false,
             'I...wa...yo..he...mis....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             42,
             'Monster Shadow',
             true,
             false,
             'I...wa...yo..he...mis....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             42,
             'Monster Shadow',
             true,
             false,
             'I...wa...yo..he...mis....');

 {**Level 43 monsters **}

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             43,
             'Evil Spirit',
             true,
             false,
             'I can see that your brain is damaged! hoho...');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             43,
             'Evil Spirit',
             true,
             false,
             'I can see that your brain is damaged! hoho...');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             43,
             'Evil Spirit',
             true,
             false,
             'I can see that your brain is damaged! hoho...');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             43,
             'Evil Spirit',
             true,
             false,
             'I can see that your brain is damaged! hoho...');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             43,
             'Evil Spirit',
             true,
             false,
             'I can see that your brain is damaged! hoho...');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             43,
             'Evil Spirit',
             true,
             false,
             'I can see that your brain is damaged! hoho...');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             43,
             'Evil Spirit',
             true,
             false,
             'I can see that your brain is damaged! hoho...');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             43,
             'Evil Spirit',
             true,
             false,
             'I can see that your brain is damaged! hoho...');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             43,
             'Evil Spirit',
             true,
             false,
             'I can see that your brain is damaged! hoho...');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             43,
             'Evil Spirit',
             true,
             false,
             'I can see that your brain is damaged! hoho...');

 {**Level 44 monsters **}

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             44,
             'Dark Ghoul',
             true,
             false,
             'Gnnnnnnnnnnn!');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             44,
             'Dark Ghoul',
             true,
             false,
             'Gnnnnnnnnnnn!');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             44,
             'Dark Ghoul',
             true,
             false,
             'Gnnnnnnnnnnn!');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             44,
             'Dark Ghoul',
             true,
             false,
             'Gnnnnnnnnnnn!');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             44,
             'Dark Ghoul',
             true,
             false,
             'Gnnnnnnnnnnn!');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             44,
             'Dark Ghoul',
             true,
             false,
             'Gnnnnnnnnnnn!');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             44,
             'Dark Ghoul',
             true,
             false,
             'Gnnnnnnnnnnn!');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             44,
             'Dark Ghoul',
             true,
             false,
             'Gnnnnnnnnnnn!');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             44,
             'Dark Ghoul',
             true,
             false,
             'Gnnnnnnnnnnn!');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             44,
             'Dark Ghoul',
             true,
             false,
             'Gnnnnnnnnnnn!');

 {**Level 45 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Shadowbeast',
             true,
             false,
             'Grrowl! Need food badly!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Shadowbeast',
             true,
             false,
             'Grrowl! Need food badly!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Shadowbeast',
             true,
             false,
             'Grrowl! Need food badly!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Shadowbeast',
             true,
             false,
             'Grrowl! Need food badly!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Shadowbeast',
             true,
             false,
             'Grrowl! Need food badly!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Shadowbeast',
             true,
             false,
             'Grrowl! Need food badly!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Shadowbeast',
             true,
             false,
             'Grrowl! Need food badly!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Shadowbeast',
             true,
             false,
             'Grrowl! Need food badly!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Shadowbeast',
             true,
             false,
             'Grrowl! Need food badly!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Shadowbeast',
             true,
             false,
             'Grrowl! Need food badly!');

 {**Level 46 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             46,
             'Crawling Fear',
             true,
             false,
             'uuuuuuuuuuu...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             46,
             'Crawling Fear',
             true,
             false,
             'uuuuuuuuuuu...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             46,
             'Crawling Fear',
             true,
             false,
             'uuuuuuuuuuu...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             46,
             'Crawling Fear',
             true,
             false,
             'uuuuuuuuuuu...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             46,
             'Crawling Fear',
             true,
             false,
             'uuuuuuuuuuu...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             46,
             'Crawling Fear',
             true,
             false,
             'uuuuuuuuuuu...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             46,
             'Crawling Fear',
             true,
             false,
             'uuuuuuuuuuu...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             46,
             'Crawling Fear',
             true,
             false,
             'uuuuuuuuuuu...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             46,
             'Crawling Fear',
             true,
             false,
             'uuuuuuuuuuu...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             46,
             'Crawling Fear',
             true,
             false,
             'uuuuuuuuuuu...');

 {**Level 47 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             47,
             'Fallen Angel',
             true,
             false,
             'I must destroy everything...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             47,
             'Fallen Angel',
             true,
             false,
             'I must destroy...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             47,
             'Fallen Angel',
             true,
             false,
             'I must destroy everything...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             47,
             'Fallen Angel',
             true,
             false,
             'I must destroy everything...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             47,
             'Fallen Angel',
             true,
             false,
             'I must destroy everything...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             47,
             'Fallen Angel',
             true,
             false,
             'I must destroy everything...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             47,
             'Fallen Angel',
             true,
             false,
             'I must destroy everything...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             47,
             'Fallen Angel',
             true,
             false,
             'I must destroy everything...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             47,
             'Fallen Angel',
             true,
             false,
             'I must destroy everything...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             47,
             'Fallen Angel',
             true,
             false,
             'I must destroy everything...');

 {**Level 48 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             48,
             'Freak Lord',
             true,
             false,
             'Yes, I am mad.');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             48,
             'Freak Lord',
             true,
             false,
             'Yes, I am quite mad...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             48,
             'Freak Lord',
             true,
             false,
             'Yes, I am a sick person!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             48,
             'Freak Lord',
             true,
             false,
             'Say hello to my friend!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             48,
             'Freak Lord',
             true,
             false,
             'Do you have faith in death?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             48,
             'Freak Lord',
             true,
             false,
             'I have nothing to say...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             48,
             'Freak Lord',
             true,
             false,
             'Check this out!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             48,
             'Freak Lord',
             true,
             false,
             'You have mistaken me for someone!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             48,
             'Freak Lord',
             true,
             false,
             'Welcome to meet my sword!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             48,
             'Freak Lord',
             true,
             false,
             'Do you have any experiences to share with me?');

 {**Level 49 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             49,
             'Creepy Thing',
             true,
             false,
             'Ssssssssss....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             49,
             'Creepy Thing',
             true,
             false,
             'Ssssssssss....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             49,
             'Creepy Thing',
             true,
             false,
             'Ssssssssss....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             49,
             'Creepy Thing',
             true,
             false,
             'Ssssssssss....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             49,
             'Creepy Thing',
             true,
             false,
             'Ssssssssss....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             49,
             'Creepy Thing',
             true,
             false,
             'Ssssssssss....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             49,
             'Creepy Thing',
             true,
             false,
             'Ssssssssss....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             49,
             'Creepy Thing',
             true,
             false,
             'Ssssssssss....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             49,
             'Creepy Thing',
             true,
             false,
             'Ssssssssss....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             49,
             'Creepy Thing',
             true,
             false,
             'Ssssssssss....');

 reset_monsters3;

end;

Procedure Reset_Monsters;
begin

 counter:=0;

 {assign}
 assign(monsterfile,monfile);

 {rewrite}
 {$I-}rewrite(monsterfile);{$I+}
 if IOResult<>0 then unable_to_create(Monfile);

 {**Level 1 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             1,
             0,
             1,
             'Beggar',
             true,
             false,
             'I''m gonna kick Your Butt!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             2,
             'Thief',
             true,
             false,
             'Hihi!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             3,
             'Beggar',
             true,
             false,
             'I am old and weak!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             4,
             'Guard',
             true,
             false,
             'Do not pass me!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             5,
             'Punk',
             true,
             false,
             'Just want your life!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             6,
             'Rogue',
             true,
             false,
             'Hmm..lets see...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             7,
             'Old man',
             true,
             false,
             'Spare me! Spare me!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             8,
             'Wrestler',
             true,
             false,
             'Howdy! A fight it shall be!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             9,
             'Insane Woman',
             true,
             false,
             'Ihhhhh!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             10,
             'Gnoll',
             true,
             false,
             'Let me help you!');

  {**Level 2 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             12,
             'Small Troll',
             true,
             false,
             'Grrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             12,
             'Insane Ape',
             true,
             false,
             'Uhuhuhuhuhuhu!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             12,
             'Giant Gnoll',
             true,
             false,
             'My spear in your head! Good!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             12,
             'Angry Centipede',
             true,
             false,'....');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             12,
             'Small Spider',
             true,
             false,
             'Sssaaayy...Come over here!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             12,
             'Assassin',
             true,
             false,
             'Interesting throat you have...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             12,
             'Weak Dwarf',
             true,
             false,
             'Interesting neck you have...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             12,
             'Amazon',
             true,
             false,
             'Knife! Knife! Knife!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             12,
             'Insane Eagle',
             true,
             false,
             'Krrraaa!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             12,
             'Rabid worm',
             true,
             false,'...');

  {**Level 3 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             13,
             'Medium Troll',
             true,
             false,
             'Humm Humm...Kill!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             13,
             'Psycho Ape',
             true,
             false,
             'Ahahahahaaaa!');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             13,
             'Pet Dragon',
             true,
             false,
             'Are you my dad?');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             13,
             'Ugly Mummy',
             true,
             false,
             'Where did you come from?');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             13,
             'Dwarf Wrestler',
             true,
             false,
             'I need practice!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             13,
             'Ugly Woodman',
             true,
             false,
             'Grunt grunt!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             13,
             'Small Griffin',
             true,
             false,
             'Who are you?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             13,
             'Madman',
             true,
             false,
             'Kill! Kill! Kill! Kill!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             13,
             'Crazy Guard',
             true,
             false,
             'Nobody trespasses here! NOBODY!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             13,
             'Drunk Mutant',
             true,
             false,
             'Glurg Glurg... Hick!');

  {**Level 4 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             14,
             'Mad Troll',
             true,
             false,
             'Grrr! Want to kill!!!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             14,
             'Baby Godzilla',
             true,
             false,
             'Rrrrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             14,
             'Baby Dragon',
             true,
             false,
             'Schhhh! I''m trying to sleep!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             14,
             'Fat Mummy',
             true,
             false,
             'You = food!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             14,
             'Freak',
             true,
             false,
             'Hihi!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             14,
             'Rabid ant',
             true,
             false,'....');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             14,
             'Dwarf Zombie',
             true,
             false,
             'Gagagagaga!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             14,
             'Dwarf Punk',
             true,
             false,
             'Another skull to bash!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             14,
             'Mad Priest',
             true,
             false,
             'I have a solution....!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             14,
             'Psycho',
             true,
             false,
             'Hehehe!');

  {**Level 5 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             15,
             'Judge',
             true,
             false,
             'I have the truth!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             15,
             'Unknown Reptile',
             true,
             false,
             'Ssssssss!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             15,
             'Micro Dragon',
             true,
             false,
             'Ssssssss!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             15,
             'Insane Ranger',
             true,
             false,
             'Meet Sword, my best friend!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             15,
             'Grift Ghoul',
             true,
             false,
             'Ohhhhh!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             15,
             'Grave Robber',
             true,
             false,
             'Who are you?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             15,
             'One-eyed Mutant',
             true,
             false,
             'I shall kill you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             15,
             'Psycho',
             true,
             false,
             'Hahaha! Come over here!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             15,
             'Gnoll',
             true,
             false,
             'Hey and Hoo, and a bottle of Rum!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             15,
             'Disgusting Man',
             true,
             false,
             'What do you want slimeball?');

  {**Level 6 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             16,
             'Troll Chief',
             true,
             false,
             'Looking for gold huh? Well, you have met me insted!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             16,
             'Lister',
             true,
             false,
             'Smeg off!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             16,
             'Dragonsoul',
             true,
             false,
             'You cannot see me...but feel me you can!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             16,
             'Lost Soul',
             true,
             false,
             'You cannot see me...but feel me you can!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             16,
             'Golden Guardian',
             true,
             false,
             'You are an evildoer!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             16,
             'Infantry Orc',
             true,
             false,
             'Have you seen my regiment?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             16,
             'Orc Sergeant',
             true,
             false,
             'Deserter huh?! Well I am gonna teach you a lesson!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             16,
             'Splatter Monk',
             true,
             false,
             'My profession is to dismember people!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             16,
             'Large Monk',
             true,
             false,
             'I salute you! You seem to be ready to die!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             16,
             'Crazy Man',
             true,
             false,
             'Lalalalalala!');

  {**Level 7 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             17,
             'Large Snake',
             true,
             false,
             'Ssssss...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             17,
             'Orc',
             true,
             false,
             'Strange...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             17,
             'Sword Champion',
             true,
             false,
             'Let'+chr(39)+'s fight!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             17,
             'Orc Lieutenant',
             true,
             false,
             'Let us fight!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             17,
             'Stone Elf',
             true,
             false,
             'You fight for darkness!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             17,
             'Uruk-Hai',
             true,
             false,
             'Ha! Another victim!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             17,
             'Gnoll',
             true,
             false,
             'Haven'+chr(39)+'t seen you here before!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             17,
             'Monk',
             true,
             false,
             'I am very skilled! You look like trash to me!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             17,
             'Wizard',
             true,
             false,
             'Kazaam!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             17,
             'Lion',
             true,
             false,
             'Grrrrrr!');

  {**Level 8 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             18,
             'Unknown Reptile',
             true,
             false,
             'Tssssss!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             18,
             'Sandworm',
             true,
             false,'.....!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             18,
             'Orc Officer',
             true,
             false,
             'Halt! Fight me!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             18,
             'Orc General',
             true,
             false,
             'Stop! Bloody deserter!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             18,
             'Bronze Elf',
             true,
             false,
             'I have arrows with your name on them!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             18,
             'Glowing Gnoll',
             true,
             false,
             'Do you belive in reincarnation?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             18,
             'Warrior',
             true,
             false,
             'Dog!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             18,
             'Strange Thing',
             true,
             false,
             'Mmmm....');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             18,
             'Warrior',
             true,
             false,
             'Dirty hound!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             18,
             'Elf Chieftain',
             true,
             false,
             'Anything to say before you die?');

  {**Level 9 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             19,
             'Sabre Wulf',
             true,
             false,
             'Grrrrr!!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             19,
             'Dwarf King',
             true,
             false,
             'Salute your superior!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             19,
             'Great Paladin',
             true,
             false,
             'Ready to meet death!? Pagan Scum!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             19,
             'Orc Chieftain',
             true,
             false,
             'I am very good with my weapon!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             19,
             'Silver Elf',
             true,
             false,
             'Hi there! Nice day to fight!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             19,
             'Insane Gnoll',
             true,
             false,
             'Hihihih!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             19,
             'Unknown Monster',
             true,
             false,
             'Rraaaahh!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             19,
             'Orc Noble',
             true,
             false,
             'Are you kidding? You fight me!? Haha!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             19,
             'Severe Madman',
             true,
             false,
             'Please! Drop your weapon!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             19,
             'Uruk-Hai',
             true,
             false,
             'Haaaaaiii! I am Uruk-Hai!');

  {**Level 10 monsters **}
 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Orc Lord',
             true,
             false,
             'Cheap punk!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Grifter',
             true,
             false,
             'Mohahaha!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Surpriser',
             true,
             false,
             'Zooohh!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Dark Ranger',
             true,
             false,
             'Nice monkey suit! haha!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Silver Mage',
             true,
             false,
             'I'+chr(39)+'m gonna ZAP you to hell!');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Medusa',
             true,
             false,
             'Look here adventurer!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Dripper',
             true,
             false,
             'Pssssss...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Mercenary',
             true,
             false,
             'Why must I always meet worthless punks like you?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Mercenary',
             true,
             false,
             'Well, I DO need some practice!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Bounty Hunter',
             true,
             false,
             'Are you wanted somewhere? Well, I'+chr(39)+'ll kill you anyway!');

 {**Level 11 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Medusas First Head',
             true,
             false,
             'Look at me!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Medusas Second Head',
             true,
             false,
             'Look into my eyes!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Gnoll',
             true,
             false,
             'I will not harm you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Gnoll Chief',
             true,
             false,
             'Hey! Fatso!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Evil Gnoll',
             true,
             false,
             'Ha!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Evil Gnoll',
             true,
             false,
             'You are brave...but foolish!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Medusas Third Head',
             true,
             false,
             'Do you love me?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Catholic Noble',
             true,
             false,
             'Rejoice with God!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Protestant Noble',
             true,
             false,
             'Pagan scum!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Deathbringer',
             true,
             false,
             'Bahhh!');

  {**Level 12 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Bugbear',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Dront',
             true,
             false,
             'Hmmmmm...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Giant Dront',
             true,
             false,
             'Hmmmmm...To kill or to be killed, that is the question.');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Dark Soul',
             true,
             false,
             'Listen to me!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Gorgol',
             true,
             false,
             'Oiiiiiii!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Orc Leader',
             true,
             false,
             'Can I dunk your head?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Bugbear',
             true,
             false,
             'Grrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Bugbear',
             true,
             false,
             'Morrr!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Mad Mage',
             true,
             false,
             'Mohahaha!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Jester',
             true,
             false,
             'I can make you laugh!');

 {**Level 13 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Blind Fool',
             true,
             false,
             'Can you help me son?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Rude Boy',
             true,false,
             'Time to die filthy scum!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Big Bad Wolf',
             true,
             false,
             'Grrrrrr...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Floating Wizard',
             true,
             false,
             'Zazza Yrga Nihla Yum!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Dragon of Fire',
             true,
             false,
             'You make me angry!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Red Dragon',
             true,
             false,
             'Burn in hell!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'White Dragon',
             true,
             false,
             'Salute me! The great Incinerator!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Spider Dragon',
             true,
             false,
             'I would like to eat you! May I?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Ghoul',
             true,
             false,
             'I bring death to YOU!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'White Elf',
             true,
             false,
             'Mmmmmm...you seem to be ok!');

 {**Level 14 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Gooie',
             true,
             false,
             'Pssssss...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Dark Phantom',
             true,
             false,
             'Soon you will be dead!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Scorpion',
             true,
             false,
             '...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Mutant Dwarf',
             true,
             false,
             'Gnnrghh!');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Flying Vaporizer',
             true,
             false,
             'Svoosch!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Black Mage',
             true,
             false,
             'Ready to die?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Dark Knight',
             true,
             false,
             'Get ready to recieve my blows!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Thief',
             true,
             false,
             'I'+chr(39)+'m gonna slice ya!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,'Wood Elf',
             true,
             false,
             'Haven'+chr(39)+'t I seen you before?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Black Scorpion',
             true,
             false,'...');

 {**Level 15 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Giant Scorpion',
             true,
             false,'...');

 add_monster(true,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Small Ape',
             true,
             false,
             'Hello! I am a monkey!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Capricorn',
             true,
             false,
             'Ihihihih!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Nightmare',
             true,
             false,
             'Uuuuuuuu!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Dark Hoodlum',
             true,
             false,
             'Cut ya! I'+chr(39)+'m gonna cut ya!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Lurking Grudge',
             true,
             false,
             'Grrrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Cobra',
             true,
             false,
             'Ssssss..');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Troll General',
             true,
             false,
             'Gromf!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Hellcat',
             true,
             false,
             'Frssss!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Leper Woman',
             true,
             false,
             'Scheeeee!');

  {**Level 16 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Mutant Bulldog',
             true,
             false,
             'Grow! Grow! Grow!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Ogre',
             true,
             false,
             'Hum Hum! Me big, you weak!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Huge Ant',
             true,
             false,'...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Ranger',
             true,
             false,
             'Death is in the air...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Master Strangler',
             true,
             false,
             'Nice throat of yours!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Grandpa Dragon',
             true,
             false,
             'Time to toast!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Stabbing Master',
             true,
             false,
             'I would like to kill you!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             20,
             'Red Spider',
             true,
             false,
             'Nam nam! Food!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Draconian',
             true,
             false,
             'Aaaatttaaaack!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             20,
             'Elite Guard',
             true,
             false,
             'My profession is to kill people!');

  {**Level 17 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             21,
             'Orc Scoundrel',
             true,
             false,
             'Hi there! Please surrender!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             21,
             'Giant Ant',
             true,
             false,'....!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             21,
             'Rabid hound',
             true,
             false,
             'Grrrr!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             21,
             'Red Witch',
             true,
             false,
             'Hello darling!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             21,
             'Club Champion',
             true,
             false,
             'Me CHAMP! You DEAD!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             21,
             'Mad Woman',
             true,
             false,
             'Grrrr!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             21,
             'Scum of the Earth',
             true,
             false,
             'You again! Hrmmm...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             21,
             'Red Wizard',
             true,
             false,
             'God damn traitor!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             21,
             'Soldier of Fortune',
             true,
             false,
             'Good, you seem to be a suitable victim!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             21,
             'Zuul Mercenary',
             true,
             false,
             'I shall sacrifice you to my God!');

 {**Level 18 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             22,
             'Ghoul',
             true,
             false,
             'Buuu!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             22,
             'Giant Eagle',
             true,
             false,
             'Kraaaa!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             22,
             'Gnome Warrior',
             true,
             false,
             'Hehehe...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             22,
             'Baby Dront',
             true,
             false,
             'Daddy!?');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             22,
             'Flying Bear',
             true,
             false,
             'Grrrr...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             22,
             'Uruk-Hai',
             true,
             false,
             'Me Uruk-Hai! You are doomed!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             22,
             'Dunedain',
             true,
             false,
             'Cut the smalltalk...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             22,
             'Dream Lord',
             true,
             false,
             'Is this the REAL reality?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             22,
             'Fallguy',
             true,
             false,
             'Everbody'+chr(39)+'s on my back!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             22,
             'Renegade Troll',
             true,
             false,
             'You want my gold huh!? Come and get it!');

 {**Level 19 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             23,
             'Small Dront',
             true,
             false,
             'Aiiieee!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             23,
             'Wonder of Evil',
             true,
             false,
             'Zooming in on your brain!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             23,
             'Renegade Orc',
             true,
             false,
             'Salute your master! Punk!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             23,
             'Renegade Orc',
             true,
             false,
             'Do you have any money?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             23,
             'Hobgoblin',
             true,
             false,
             'I am quite good with my dagger...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             23,
             'Uruk-Hai',
             true,
             false,
             'Surrender or perish!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             23,
             'Sheriff',
             true,
             false,
             'You are under arrest!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             23,
             'Ghostrider',
             true,
             false,
             'Woooooaaa!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             23,
             'Mountain Tiger',
             true,
             false,
             'Grrrrrrr!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             23,
             'Mamba',
             true,
             false,
             'Ssssss...!');

 {**Level 20 monsters **}

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             24,
             'Hypnotic Snake',
             true,
             false,
             'Ssssssss...');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             24,
             'Dragon Owl',
             true,
             false,
             'Ohohoho!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             24,
             'Huge Dront',
             true,
             false,
             'You are trouble! You must die!');

 add_monster(false,                     { Armoruser }
             false,
             0,
             0,
             24,
             'Giant Eagle',
             true,
             false,
             'Watch your head!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             24,
             'Wizard',
             true,
             false,
             'Go to hell! Damn adventurer!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             24,
             'Orc Teenager',
             true,
             false,
             'Hihihi!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             24,
             'Orc Child',
             true,
             false,
             'Hehehe!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             24,
             'Celtic Warrior',
             true,
             false,
             'I have come far in my search!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             24,
             'Viking Leader',
             true,
             false,
             'You can'+chr(39)+'t stop me!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             24,
             'Green Dwarf',
             true,
             false,
             'Let'+chr(39)+'s have some fun!');

 {**Level 21 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Barbarian',
             true,
             false,
             'Meet my Sword!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Master Barbarian',
             true,
             false,
             'Nice weapon you have! Haha!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Renegade Elf',
             true,
             false,
             'You are pathetic! Do you know that!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Dwarf Lord',
             true,
             false,
             'Killed any Dwarves have ya!? Well, I shall stop it!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Dwarf King',
             true,
             false,
             'Screaming doesn'+chr(39)+'t help...');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Bard',
             true,
             false,
             'I have a battle song for you!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Thief',
             true,
             false,
             'Hi!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Gnoll',
             true,
             false,
             'Surprise!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Villain',
             true,
             false,
             'Howdy! Gimme your life!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             25,
             'Red Dwarf',
             true,
             false,
             'You look bad to me! Let'+chr(39)+'s swing the axe!');

 {**Level 22 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Shadow Knight',
             true,
             false,
             'Blow the Horn for battle!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Shadow Knight',
             true,
             false,
             'Blow the Horn for battle!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Shadow Knight',
             true,
             false,
             'Blow the Horn for battle!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Shadow Knight',
             true,
             false,
             'Blow the Horn for battle!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Shadow Knight',
             true,
             false,
             'Hi there stranger!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Shadow Knight',
             true,
             false,
             'Have yoy seen my comrades?');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Shadow Knight',
             true,
             false,
             '...!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Shadow Knight',
             true,
             false,
             ' =)');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Shadow Knight',
             true,
             false,
             'Once upon a time there was...');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             35,
             'Shadow Knight',
             true,
             false,
             'Have you seen my horn?');

 {**Level 23 monsters **}

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Gargoyle',
             true,
             false,
             'Tihihihi!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Gargoyle',
             true,
             false,
             'Tihihihi!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Gargoyle',
             true,
             false,
             'Tihihihi!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Gargoyle',
             true,
             false,
             'Tihihihi!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Gargoyle',
             true,
             false,
             'Tihihihi!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Gargoyle',
             true,
             false,
             'Tihihihi!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Gargoyle',
             true,
             false,
             'Tihihihi!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Gargoyle',
             true,
             false,
             'Tihihihi!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Gargoyle',
             true,
             false,
             'Tihihihi!');

 add_monster(false,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Gargoyle',
             true,
             false,
             'Tihihihi!');

 {**Level 24 monsters **}

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Wolfrider',
             true,
             false,
             'Grraaaahh!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Wolfrider',
             true,
             false,
             'Grraaaahh!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Wolfrider',
             true,
             false,
             'Grraaaahh!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Wolfrider',
             true,
             false,
             'Grraaaahh!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Wolfrider',
             true,
             false,
             'Grraaaahh!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Wolfrider',
             true,
             false,
             'Grraaaahh!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Wolfrider',
             true,
             false,
             'Grraaaahh!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Wolfrider',
             true,
             false,
             'Grraaaahh!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Wolfrider',
             true,
             false,
             'Grraaaahh!');

 add_monster(true,                     { Armoruser }
             true,
             0,
             0,
             45,
             'Wolfrider',
             true,
             false,
             'Grraaaahh!');


 reset_monsters2;

 {close}
 {$I-}close(monsterfile);{$I+}
 if IOResult<>0 then unable_to_close(Monfile);


end;
end.
