{$IFNDEF MSDOS}
{$I DEFINES.INC}
{$ENDIF}
{

Copyright 2007 Jakob Dangarden

 This file is part of Usurper.

    Usurper is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Usurper is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Usurper; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
}

unit EdMonst;

interface

procedure Reset_Monsters; {All the Monsters in Usurper}

implementation

uses
  file_io, init, addmonst,
  edmonst2; {more monsters are here in edmonst2}

procedure Reset_Monsters2;
begin

  {**Level 25 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Wandering Ghoul',
    True,
    False,
    'Greetings adventurer...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Wandering Ghoul',
    True,
    False,
    'Greetings adventurer...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Wandering Ghoul',
    True,
    False,
    'Greetings adventurer...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Wandering Ghoul',
    True,
    False,
    'Greetings adventurer...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Wandering Ghoul',
    True,
    False,
    'Greetings adventurer...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Wandering Ghoul',
    True,
    False,
    'Greetings adventurer...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Wandering Ghoul',
    True,
    False,
    'Greetings adventurer...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Wandering Ghoul',
    True,
    False,
    'Greetings adventurer...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Wandering Ghoul',
    True,
    False,
    'Greetings adventurer...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Wandering Ghoul',
    True,
    False,
    'Greetings adventurer...');

  {**Level 26 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    26,
    'Cave Gorilla',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    26,
    'Cave Gorilla',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    26,
    'Cave Gorilla',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    26,
    'Cave Gorilla',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    26,
    'Cave Gorilla',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    26,
    'Cave Gorilla',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    26,
    'Cave Gorilla',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    26,
    'Cave Gorilla',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    26,
    'Cave Gorilla',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    26,
    'Cave Gorilla',
    True,
    False,
    'Grrrrr!');

  {**Level 27 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    27,
    'Troll Master',
    True,
    False,
    'Hehehe...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    27,
    'Troll Master',
    True,
    False,
    'Hehehe...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    27,
    'Troll Master',
    True,
    False,
    'Hehehe...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    27,
    'Troll Master',
    True,
    False,
    'Hehehe...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    27,
    'Troll Master',
    True,
    False,
    'Hehehe...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    27,
    'Troll Master',
    True,
    False,
    'Hehehe...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    27,
    'Troll Master',
    True,
    False,
    'Hehehe...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    27,
    'Troll Master',
    True,
    False,
    'Hehehe...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    27,
    'Troll Master',
    True,
    False,
    'Hehehe...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    27,
    'Troll Master',
    True,
    False,
    'Hehehe...');

  {**Level 28 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    28,
    'Godzilla',
    True,
    False,
    'Uhhh?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    28,
    'Godzilla',
    True,
    False,
    'Uhhh?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    28,
    'Godzilla',
    True,
    False,
    'Uhhh?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    28,
    'Godzilla',
    True,
    False,
    'Uhhh?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    28,
    'Godzilla',
    True,
    False,
    'Uhhh?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    28,
    'Godzilla',
    True,
    False,
    'Uhhh?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    28,
    'Godzilla',
    True,
    False,
    'Uhhh?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    28,
    'Godzilla',
    True,
    False,
    'Uhhh?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    28,
    'Godzilla',
    True,
    False,
    'Uhhh?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    28,
    'Godzilla',
    True,
    False,
    'Uhhh?');

  {**Level 29 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    29,
    'Nocturne',
    True,
    False,
    'Ihhhhhhh!!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    29,
    'Nocturne',
    True,
    False,
    'Ihhhhhhh!!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    29,
    'Nocturne',
    True,
    False,
    'Ihhhhhhh!!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    29,
    'Nocturne',
    True,
    False,
    'Ihhhhhhh!!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    29,
    'Nocturne',
    True,
    False,
    'Ihhhhhhh!!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    29,
    'Nocturne',
    True,
    False,
    'Ihhhhhhh!!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    29,
    'Nocturne',
    True,
    False,
    'Ihhhhhhh!!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    29,
    'Nocturne',
    True,
    False,
    'Ihhhhhhh!!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    29,
    'Nocturne',
    True,
    False,
    'Ihhhhhhh!!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    29,
    'Nocturne',
    True,
    False,
    'Ihhhhhhh!!');

  {**Level 30 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    30,
    'Gargoyle Lord',
    True,
    False,
    'Food! How nice!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    30,
    'Gargoyle Lord',
    True,
    False,
    'Food! How nice!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    30,
    'Gargoyle Lord',
    True,
    False, 'Food! How nice!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    30,
    'Gargoyle Lord',
    True,
    False,
    'Food! How nice!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    30,
    'Gargoyle Lord',
    True,
    False,
    'Food! How nice!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    30,
    'Gargoyle Lord',
    True,
    False,
    'Food! How nice!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    30,
    'Gargoyle Lord',
    True,
    False,
    'Food! How nice!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    30,
    'Gargoyle Lord',
    True,
    False,
    'Food! How nice!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    30,
    'Gargoyle Lord',
    True,
    False,
    'Food! How nice!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    30,
    'Gargoyle Lord',
    True,
    False,
    'Food! How nice!');

  {**Level 31 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    31,
    'Veteran Ranger',
    True,
    False,
    'Howdy!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    31,
    'Veteran Ranger',
    True,
    False,
    'Howdy!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    31,
    'Veteran Ranger',
    True,
    False,
    'Howdy!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    31,
    'Veteran Ranger',
    True,
    False,
    'Howdy!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    31,
    'Veteran Ranger',
    True,
    False,
    'Howdy!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    31,
    'Veteran Ranger',
    True,
    False,
    'Howdy!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    31,
    'Veteran Ranger',
    True,
    False,
    'Howdy!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    31,
    'Veteran Ranger',
    True,
    False,
    'Howdy!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    31,
    'Veteran Ranger',
    True,
    False,
    'Howdy!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    31,
    'Veteran Ranger',
    True,
    False,
    'Howdy!');

  {**Level 32 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    32,
    'Large Troll',
    True,
    False,
    'Ready for pain!?');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    32,
    'Huge Troll',
    True,
    False,
    'Done with your prayers?');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    32,
    'Small Troll',
    True,
    False,
    'Meet my Club!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    32,
    'Medium Troll',
    True,
    False,
    'Charge!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    32,
    'Giant Troll',
    True,
    False,
    'Beg for mercy or meeet your destiny!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    32,
    'Large Troll',
    True,
    False,
    'Aaaaarghhhh!!!!!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    32,
    'Large Troll',
    True,
    False,
    'Prepare for battle!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    32,
    'Large Troll',
    True,
    False,
    'DIE!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    32,
    'Troll',
    True,
    False,
    'Another visitor! Stay a while...stay forver!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    32,
    'Troll',
    True,
    False,
    'I have punks like you for breakfast!');

  {**Level 33 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    33,
    'Gorilla Lord',
    True,
    False,
    'Gruuuuu!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    33,
    'Gorilla Lord',
    True,
    False,
    'Gruuuuu!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    33,
    'Gorilla Lord',
    True,
    False,
    'Gruuuuu!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    33,
    'Gorilla Lord',
    True,
    False,
    'Gruuuuu!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    33,
    'Gorilla Lord',
    True,
    False,
    'Gruuuuu!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    33,
    'Gorilla Lord',
    True,
    False,
    'Gruuuuu!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    33,
    'Gorilla Lord',
    True,
    False,
    'Gruuuuu!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    33,
    'Gorilla Lord',
    True,
    False,
    'Gruuuuu!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    33,
    'Gorilla Lord',
    True,
    False,
    'Gruuuuu!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    33,
    'Gorilla Lord',
    True,
    False,
    'Gruuuuu!?');

  {**Level 34 monsters **}
  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    34,
    'Orc Warlord',
    True,
    False,
    'Haha! You against me! What has the world come to?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    34,
    'Orc Warlord',
    True,
    False,
    'Haha! You against me! What has the world come to ?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    34,
    'Orc Warlord',
    True,
    False,
    'Mmmmm....you will do!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    34,
    'Orc Warlord',
    True,
    False,
    'Battle practice! Ex-slave?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    34,
    'Grinning Ape',
    True,
    False,
    'Tchiii! Tchi! Tchi!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    34,
    'Grinning Ape',
    True,
    False,
    'Tchiii! Tchi! Tchi!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    34,
    'Grinning Ape',
    True,
    False,
    'Tchiii! Tchi! Tchi!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    34,
    'Grinning Ape',
    True,
    False,
    'Tchiii! Tchi! Tchi!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    34,
    'Grinning Ape',
    True,
    False,
    'Tchiii! Tchi! Tchi!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    34,
    'Grinning Ape',
    True,
    False,
    'Tchiii! Tchi! Tchi!');

  {**Level 35 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Nameless Fear',
    True,
    False,
    'Zzzzzzzzzzz...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Nameless Fear',
    True,
    False,
    'Zzzzzzzzzzz...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Nameless Fear',
    True,
    False,
    'Zzzzzzzzzzz...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Nameless Fear',
    True,
    False,
    'Zzzzzzzzzzz...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Nameless Fear',
    True,
    False,
    'Zzzzzzzzzzz...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Nameless Fear',
    True,
    False,
    'Zzzzzzzzzzz...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Nameless Fear',
    True,
    False,
    'Zzzzzzzzzzz...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Nameless Fear',
    True,
    False,
    'Zzzzzzzzzzz...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Nameless Fear',
    True,
    False,
    'Zzzzzzzzzzz...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Nameless Fear',
    True,
    False,
    'Zzzzzzzzzzz...');

  {**Level 36 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    36,
    'Blood Guardian',
    True,
    False,
    'Go away!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    36,
    'Blood Guardian',
    True,
    False,
    'Go away!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    36,
    'Blood Guardian',
    True,
    False,
    'Go away!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    36,
    'Blood Guardian',
    True,
    False,
    'Go away!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    36,
    'Blood Guardian',
    True,
    False,
    'Buzz Off!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    36,
    'Blood Guardian',
    True,
    False,
    'Buzz Off!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    36,
    'Blood Guardian',
    True,
    False,
    'Buzz Off!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    36,
    'Blood Guardian',
    True,
    False,
    'Buzz Off!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    36,
    'Blood Guardian',
    True,
    False,
    'Buzz Off!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    36,
    'Blood Guardian',
    True,
    False,
    'Get lost!');

  {**Level 37 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    37,
    'Creeping Fear',
    True,
    False,
    'Food! Food! Food!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    37,
    'Creeping Fear',
    True,
    False,
    'Food! Food! Food!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    37,
    'Creeping Fear',
    True,
    False,
    'Food! Food! Food!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    37,
    'Creeping Fear',
    True,
    False,
    'Food! Food! Food!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    37,
    'Creeping Fear',
    True,
    False,
    'Kill! Kill! Kill!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    37,
    'Creeping Fear',
    True,
    False,
    'Kill! Kill! Kill!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    37,
    'Creeping Fear',
    True,
    False,
    'Kill! Kill! Kill!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    37,
    'Creeping Fear',
    True,
    False,
    'Kill! Kill! Kill!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    37,
    'Creeping Fear',
    True,
    False,
    'Kill! Kill! Kill!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    37,
    'Creeping Fear',
    True,
    False,
    'Kill! Kill! Kill!');

  {**Level 38 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    38,
    'Cat Woman',
    True,
    False,
    'A great day for battle!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    38,
    'Cat Woman',
    True,
    False,
    'A great day for battle!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    38,
    'Cat Woman',
    True,
    False,
    'A great day for battle!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    38,
    'Cat Woman',
    True,
    False,
    'A great day for battle!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    38,
    'Cat Woman',
    True,
    False,
    'A great day for battle!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    38,
    'Cat Woman',
    True,
    False,
    'A great day for battle!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    38,
    'Cat Woman',
    True,
    False,
    'A great day for battle!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    38,
    'Cat Woman',
    True,
    False,
    'A great day for battle!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    38,
    'Cat Woman',
    True,
    False,
    'A great day for battle!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    38,
    'Cat Woman',
    True,
    False,
    'A great day for battle!');

  {**Level 39 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    39,
    'Dark Witch',
    True,
    False,
    'Sccchaaaa!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    39,
    'Dark Witch',
    True,
    False,
    'Sccchaaaa!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    39,
    'Dark Witch',
    True,
    False,
    'Sccchaaaa!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    39,
    'Dark Witch',
    True,
    False,
    'Sccchaaaa!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    39,
    'Dark Witch',
    True,
    False,
    'Sccchaaaa!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    39,
    'Dark Witch',
    True,
    False,
    'Sccchaaaa!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    39,
    'Dark Witch',
    True,
    False,
    'Sccchaaaa!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    39,
    'Dark Witch',
    True,
    False,
    'Sccchaaaa!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    39,
    'Dark Witch',
    True,
    False,
    'Sccchaaaa!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    39,
    'Dark Witch',
    True,
    False,
    'Sccchaaaa!');

  {**Level 40 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    40,
    'Shadow Lord',
    True,
    False,
    'You made a mistake coming down here...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    40,
    'Shadow Lord',
    True,
    False,
    'You made a mistake coming down here...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    40,
    'Shadow Lord',
    True,
    False,
    'You made a mistake coming down here...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    40,
    'Shadow Lord',
    True,
    False,
    'You made a mistake coming down here...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    40,
    'Shadow Lord',
    True,
    False,
    'You made a mistake coming down here...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    40,
    'Shadow Lord',
    True,
    False,
    'You made a mistake coming down here...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    40,
    'Shadow Lord',
    True,
    False,
    'You made a mistake coming down here...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    40,
    'Shadow Lord',
    True,
    False,
    'You made a mistake coming down here...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    40,
    'Shadow Lord',
    True,
    False,
    'You made a mistake coming down here...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    40,
    'Shadow Lord',
    True,
    False,
    'You made a mistake coming down here...');

  {**Level 41 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    41,
    'War Veteran',
    True,
    False,
    'Show me what you got!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    41,
    'War Veteran',
    True,
    False,
    'Show me what you got!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    41,
    'War Veteran',
    True,
    False,
    'Show me what you got!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    41,
    'War Veteran',
    True,
    False,
    'Show me what you got!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    41,
    'War Veteran',
    True,
    False,
    'Show me what you got!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    41,
    'War Veteran',
    True,
    False,
    'Show me what you got!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    41,
    'War Veteran',
    True,
    False,
    'Show me what you got!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    41,
    'War Veteran',
    True,
    False,
    'Show me what you got!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    41,
    'War Veteran',
    True,
    False,
    'Show me what you got!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    41,
    'War Veteran',
    True,
    False,
    'Show me what you got!');

  {**Level 42 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    42,
    'Monster Shadow',
    True,
    False,
    'I...wa...yo..he...mis....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    42,
    'Monster Shadow',
    True,
    False,
    'I...wa...yo..he...mis....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    42,
    'Monster Shadow',
    True,
    False,
    'I...wa...yo..he...mis....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    42,
    'Monster Shadow',
    True,
    False,
    'I...wa...yo..he...mis....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    42,
    'Monster Shadow',
    True,
    False,
    'I...wa...yo..he...mis....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    42,
    'Monster Shadow',
    True,
    False,
    'I...wa...yo..he...mis....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    42,
    'Monster Shadow',
    True,
    False,
    'I...wa...yo..he...mis....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    42,
    'Monster Shadow',
    True,
    False,
    'I...wa...yo..he...mis....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    42,
    'Monster Shadow',
    True,
    False,
    'I...wa...yo..he...mis....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    42,
    'Monster Shadow',
    True,
    False,
    'I...wa...yo..he...mis....');

  {**Level 43 monsters **}

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    43,
    'Evil Spirit',
    True,
    False,
    'I can see that your brain is damaged! hoho...');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    43,
    'Evil Spirit',
    True,
    False,
    'I can see that your brain is damaged! hoho...');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    43,
    'Evil Spirit',
    True,
    False,
    'I can see that your brain is damaged! hoho...');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    43,
    'Evil Spirit',
    True,
    False,
    'I can see that your brain is damaged! hoho...');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    43,
    'Evil Spirit',
    True,
    False,
    'I can see that your brain is damaged! hoho...');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    43,
    'Evil Spirit',
    True,
    False,
    'I can see that your brain is damaged! hoho...');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    43,
    'Evil Spirit',
    True,
    False,
    'I can see that your brain is damaged! hoho...');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    43,
    'Evil Spirit',
    True,
    False,
    'I can see that your brain is damaged! hoho...');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    43,
    'Evil Spirit',
    True,
    False,
    'I can see that your brain is damaged! hoho...');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    43,
    'Evil Spirit',
    True,
    False,
    'I can see that your brain is damaged! hoho...');

  {**Level 44 monsters **}

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    44,
    'Dark Ghoul',
    True,
    False,
    'Gnnnnnnnnnnn!');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    44,
    'Dark Ghoul',
    True,
    False,
    'Gnnnnnnnnnnn!');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    44,
    'Dark Ghoul',
    True,
    False,
    'Gnnnnnnnnnnn!');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    44,
    'Dark Ghoul',
    True,
    False,
    'Gnnnnnnnnnnn!');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    44,
    'Dark Ghoul',
    True,
    False,
    'Gnnnnnnnnnnn!');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    44,
    'Dark Ghoul',
    True,
    False,
    'Gnnnnnnnnnnn!');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    44,
    'Dark Ghoul',
    True,
    False,
    'Gnnnnnnnnnnn!');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    44,
    'Dark Ghoul',
    True,
    False,
    'Gnnnnnnnnnnn!');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    44,
    'Dark Ghoul',
    True,
    False,
    'Gnnnnnnnnnnn!');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    44,
    'Dark Ghoul',
    True,
    False,
    'Gnnnnnnnnnnn!');

  {**Level 45 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Shadowbeast',
    True,
    False,
    'Grrowl! Need food badly!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Shadowbeast',
    True,
    False,
    'Grrowl! Need food badly!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Shadowbeast',
    True,
    False,
    'Grrowl! Need food badly!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Shadowbeast',
    True,
    False,
    'Grrowl! Need food badly!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Shadowbeast',
    True,
    False,
    'Grrowl! Need food badly!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Shadowbeast',
    True,
    False,
    'Grrowl! Need food badly!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Shadowbeast',
    True,
    False,
    'Grrowl! Need food badly!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Shadowbeast',
    True,
    False,
    'Grrowl! Need food badly!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Shadowbeast',
    True,
    False,
    'Grrowl! Need food badly!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Shadowbeast',
    True,
    False,
    'Grrowl! Need food badly!');

  {**Level 46 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    46,
    'Crawling Fear',
    True,
    False,
    'uuuuuuuuuuu...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    46,
    'Crawling Fear',
    True,
    False,
    'uuuuuuuuuuu...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    46,
    'Crawling Fear',
    True,
    False,
    'uuuuuuuuuuu...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    46,
    'Crawling Fear',
    True,
    False,
    'uuuuuuuuuuu...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    46,
    'Crawling Fear',
    True,
    False,
    'uuuuuuuuuuu...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    46,
    'Crawling Fear',
    True,
    False,
    'uuuuuuuuuuu...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    46,
    'Crawling Fear',
    True,
    False,
    'uuuuuuuuuuu...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    46,
    'Crawling Fear',
    True,
    False,
    'uuuuuuuuuuu...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    46,
    'Crawling Fear',
    True,
    False,
    'uuuuuuuuuuu...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    46,
    'Crawling Fear',
    True,
    False,
    'uuuuuuuuuuu...');

  {**Level 47 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    47,
    'Fallen Angel',
    True,
    False,
    'I must destroy everything...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    47,
    'Fallen Angel',
    True,
    False,
    'I must destroy...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    47,
    'Fallen Angel',
    True,
    False,
    'I must destroy everything...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    47,
    'Fallen Angel',
    True,
    False,
    'I must destroy everything...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    47,
    'Fallen Angel',
    True,
    False,
    'I must destroy everything...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    47,
    'Fallen Angel',
    True,
    False,
    'I must destroy everything...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    47,
    'Fallen Angel',
    True,
    False,
    'I must destroy everything...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    47,
    'Fallen Angel',
    True,
    False,
    'I must destroy everything...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    47,
    'Fallen Angel',
    True,
    False,
    'I must destroy everything...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    47,
    'Fallen Angel',
    True,
    False,
    'I must destroy everything...');

  {**Level 48 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    48,
    'Freak Lord',
    True,
    False,
    'Yes, I am mad.');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    48,
    'Freak Lord',
    True,
    False,
    'Yes, I am quite mad...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    48,
    'Freak Lord',
    True,
    False,
    'Yes, I am a sick person!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    48,
    'Freak Lord',
    True,
    False,
    'Say hello to my friend!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    48,
    'Freak Lord',
    True,
    False,
    'Do you have faith in death?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    48,
    'Freak Lord',
    True,
    False,
    'I have nothing to say...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    48,
    'Freak Lord',
    True,
    False,
    'Check this out!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    48,
    'Freak Lord',
    True,
    False,
    'You have mistaken me for someone!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    48,
    'Freak Lord',
    True,
    False,
    'Welcome to meet my sword!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    48,
    'Freak Lord',
    True,
    False,
    'Do you have any experiences to share with me?');

  {**Level 49 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    49,
    'Creepy Thing',
    True,
    False,
    'Ssssssssss....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    49,
    'Creepy Thing',
    True,
    False,
    'Ssssssssss....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    49,
    'Creepy Thing',
    True,
    False,
    'Ssssssssss....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    49,
    'Creepy Thing',
    True,
    False,
    'Ssssssssss....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    49,
    'Creepy Thing',
    True,
    False,
    'Ssssssssss....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    49,
    'Creepy Thing',
    True,
    False,
    'Ssssssssss....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    49,
    'Creepy Thing',
    True,
    False,
    'Ssssssssss....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    49,
    'Creepy Thing',
    True,
    False,
    'Ssssssssss....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    49,
    'Creepy Thing',
    True,
    False,
    'Ssssssssss....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    49,
    'Creepy Thing',
    True,
    False,
    'Ssssssssss....');

  reset_monsters3;

end;

procedure Reset_Monsters;
begin

  counter := 0;

  {assign}
  Assign(monsterfile, monfile);

  {rewrite}
 {$I-}rewrite(monsterfile);{$I+}
  if IOResult <> 0 then unable_to_create(Monfile);

  {**Level 1 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    1,
    0,
    1,
    'Beggar',
    True,
    False,
    'I''m gonna kick Your Butt!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    2,
    'Thief',
    True,
    False,
    'Hihi!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    3,
    'Beggar',
    True,
    False,
    'I am old and weak!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    4,
    'Guard',
    True,
    False,
    'Do not pass me!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    5,
    'Punk',
    True,
    False,
    'Just want your life!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    6,
    'Rogue',
    True,
    False,
    'Hmm..lets see...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    7,
    'Old man',
    True,
    False,
    'Spare me! Spare me!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    8,
    'Wrestler',
    True,
    False,
    'Howdy! A fight it shall be!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    9,
    'Insane Woman',
    True,
    False,
    'Ihhhhh!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    10,
    'Gnoll',
    True,
    False,
    'Let me help you!');

  {**Level 2 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    12,
    'Small Troll',
    True,
    False,
    'Grrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    12,
    'Insane Ape',
    True,
    False,
    'Uhuhuhuhuhuhu!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    12,
    'Giant Gnoll',
    True,
    False,
    'My spear in your head! Good!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    12,
    'Angry Centipede',
    True,
    False, '....');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    12,
    'Small Spider',
    True,
    False,
    'Sssaaayy...Come over here!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    12,
    'Assassin',
    True,
    False,
    'Interesting throat you have...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    12,
    'Weak Dwarf',
    True,
    False,
    'Interesting neck you have...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    12,
    'Amazon',
    True,
    False,
    'Knife! Knife! Knife!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    12,
    'Insane Eagle',
    True,
    False,
    'Krrraaa!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    12,
    'Rabid worm',
    True,
    False, '...');

  {**Level 3 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    13,
    'Medium Troll',
    True,
    False,
    'Humm Humm...Kill!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    13,
    'Psycho Ape',
    True,
    False,
    'Ahahahahaaaa!');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    13,
    'Pet Dragon',
    True,
    False,
    'Are you my dad?');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    13,
    'Ugly Mummy',
    True,
    False,
    'Where did you come from?');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    13,
    'Dwarf Wrestler',
    True,
    False,
    'I need practice!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    13,
    'Ugly Woodman',
    True,
    False,
    'Grunt grunt!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    13,
    'Small Griffin',
    True,
    False,
    'Who are you?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    13,
    'Madman',
    True,
    False,
    'Kill! Kill! Kill! Kill!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    13,
    'Crazy Guard',
    True,
    False,
    'Nobody trespasses here! NOBODY!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    13,
    'Drunk Mutant',
    True,
    False,
    'Glurg Glurg... Hick!');

  {**Level 4 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    14,
    'Mad Troll',
    True,
    False,
    'Grrr! Want to kill!!!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    14,
    'Baby Godzilla',
    True,
    False,
    'Rrrrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    14,
    'Baby Dragon',
    True,
    False,
    'Schhhh! I''m trying to sleep!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    14,
    'Fat Mummy',
    True,
    False,
    'You = food!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    14,
    'Freak',
    True,
    False,
    'Hihi!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    14,
    'Rabid ant',
    True,
    False, '....');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    14,
    'Dwarf Zombie',
    True,
    False,
    'Gagagagaga!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    14,
    'Dwarf Punk',
    True,
    False,
    'Another skull to bash!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    14,
    'Mad Priest',
    True,
    False,
    'I have a solution....!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    14,
    'Psycho',
    True,
    False,
    'Hehehe!');

  {**Level 5 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    15,
    'Judge',
    True,
    False,
    'I have the truth!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    15,
    'Unknown Reptile',
    True,
    False,
    'Ssssssss!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    15,
    'Micro Dragon',
    True,
    False,
    'Ssssssss!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    15,
    'Insane Ranger',
    True,
    False,
    'Meet Sword, my best friend!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    15,
    'Grift Ghoul',
    True,
    False,
    'Ohhhhh!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    15,
    'Grave Robber',
    True,
    False,
    'Who are you?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    15,
    'One-eyed Mutant',
    True,
    False,
    'I shall kill you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    15,
    'Psycho',
    True,
    False,
    'Hahaha! Come over here!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    15,
    'Gnoll',
    True,
    False,
    'Hey and Hoo, and a bottle of Rum!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    15,
    'Disgusting Man',
    True,
    False,
    'What do you want slimeball?');

  {**Level 6 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    16,
    'Troll Chief',
    True,
    False,
    'Looking for gold huh? Well, you have met me insted!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    16,
    'Lister',
    True,
    False,
    'Smeg off!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    16,
    'Dragonsoul',
    True,
    False,
    'You cannot see me...but feel me you can!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    16,
    'Lost Soul',
    True,
    False,
    'You cannot see me...but feel me you can!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    16,
    'Golden Guardian',
    True,
    False,
    'You are an evildoer!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    16,
    'Infantry Orc',
    True,
    False,
    'Have you seen my regiment?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    16,
    'Orc Sergeant',
    True,
    False,
    'Deserter huh?! Well I am gonna teach you a lesson!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    16,
    'Splatter Monk',
    True,
    False,
    'My profession is to dismember people!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    16,
    'Large Monk',
    True,
    False,
    'I salute you! You seem to be ready to die!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    16,
    'Crazy Man',
    True,
    False,
    'Lalalalalala!');

  {**Level 7 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    17,
    'Large Snake',
    True,
    False,
    'Ssssss...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    17,
    'Orc',
    True,
    False,
    'Strange...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    17,
    'Sword Champion',
    True,
    False,
    'Let' + chr(39) + 's fight!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    17,
    'Orc Lieutenant',
    True,
    False,
    'Let us fight!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    17,
    'Stone Elf',
    True,
    False,
    'You fight for darkness!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    17,
    'Uruk-Hai',
    True,
    False,
    'Ha! Another victim!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    17,
    'Gnoll',
    True,
    False,
    'Haven' + chr(39) + 't seen you here before!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    17,
    'Monk',
    True,
    False,
    'I am very skilled! You look like trash to me!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    17,
    'Wizard',
    True,
    False,
    'Kazaam!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    17,
    'Lion',
    True,
    False,
    'Grrrrrr!');

  {**Level 8 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    18,
    'Unknown Reptile',
    True,
    False,
    'Tssssss!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    18,
    'Sandworm',
    True,
    False, '.....!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    18,
    'Orc Officer',
    True,
    False,
    'Halt! Fight me!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    18,
    'Orc General',
    True,
    False,
    'Stop! Bloody deserter!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    18,
    'Bronze Elf',
    True,
    False,
    'I have arrows with your name on them!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    18,
    'Glowing Gnoll',
    True,
    False,
    'Do you belive in reincarnation?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    18,
    'Warrior',
    True,
    False,
    'Dog!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    18,
    'Strange Thing',
    True,
    False,
    'Mmmm....');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    18,
    'Warrior',
    True,
    False,
    'Dirty hound!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    18,
    'Elf Chieftain',
    True,
    False,
    'Anything to say before you die?');

  {**Level 9 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    19,
    'Sabre Wulf',
    True,
    False,
    'Grrrrr!!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    19,
    'Dwarf King',
    True,
    False,
    'Salute your superior!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    19,
    'Great Paladin',
    True,
    False,
    'Ready to meet death!? Pagan Scum!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    19,
    'Orc Chieftain',
    True,
    False,
    'I am very good with my weapon!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    19,
    'Silver Elf',
    True,
    False,
    'Hi there! Nice day to fight!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    19,
    'Insane Gnoll',
    True,
    False,
    'Hihihih!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    19,
    'Unknown Monster',
    True,
    False,
    'Rraaaahh!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    19,
    'Orc Noble',
    True,
    False,
    'Are you kidding? You fight me!? Haha!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    19,
    'Severe Madman',
    True,
    False,
    'Please! Drop your weapon!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    19,
    'Uruk-Hai',
    True,
    False,
    'Haaaaaiii! I am Uruk-Hai!');

  {**Level 10 monsters **}
  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Orc Lord',
    True,
    False,
    'Cheap punk!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Grifter',
    True,
    False,
    'Mohahaha!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Surpriser',
    True,
    False,
    'Zooohh!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Dark Ranger',
    True,
    False,
    'Nice monkey suit! haha!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Silver Mage',
    True,
    False,
    'I' + chr(39) + 'm gonna ZAP you to hell!');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Medusa',
    True,
    False,
    'Look here adventurer!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Dripper',
    True,
    False,
    'Pssssss...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Mercenary',
    True,
    False,
    'Why must I always meet worthless punks like you?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Mercenary',
    True,
    False,
    'Well, I DO need some practice!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Bounty Hunter',
    True,
    False,
    'Are you wanted somewhere? Well, I' + chr(39) + 'll kill you anyway!');

  {**Level 11 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Medusas First Head',
    True,
    False,
    'Look at me!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Medusas Second Head',
    True,
    False,
    'Look into my eyes!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Gnoll',
    True,
    False,
    'I will not harm you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Gnoll Chief',
    True,
    False,
    'Hey! Fatso!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Evil Gnoll',
    True,
    False,
    'Ha!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Evil Gnoll',
    True,
    False,
    'You are brave...but foolish!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Medusas Third Head',
    True,
    False,
    'Do you love me?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Catholic Noble',
    True,
    False,
    'Rejoice with God!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Protestant Noble',
    True,
    False,
    'Pagan scum!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Deathbringer',
    True,
    False,
    'Bahhh!');

  {**Level 12 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Bugbear',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Dront',
    True,
    False,
    'Hmmmmm...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Giant Dront',
    True,
    False,
    'Hmmmmm...To kill or to be killed, that is the question.');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Dark Soul',
    True,
    False,
    'Listen to me!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Gorgol',
    True,
    False,
    'Oiiiiiii!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Orc Leader',
    True,
    False,
    'Can I dunk your head?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Bugbear',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Bugbear',
    True,
    False,
    'Morrr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Mad Mage',
    True,
    False,
    'Mohahaha!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Jester',
    True,
    False,
    'I can make you laugh!');

  {**Level 13 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Blind Fool',
    True,
    False,
    'Can you help me son?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Rude Boy',
    True, False,
    'Time to die filthy scum!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Big Bad Wolf',
    True,
    False,
    'Grrrrrr...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Floating Wizard',
    True,
    False,
    'Zazza Yrga Nihla Yum!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Dragon of Fire',
    True,
    False,
    'You make me angry!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Red Dragon',
    True,
    False,
    'Burn in hell!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'White Dragon',
    True,
    False,
    'Salute me! The great Incinerator!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Spider Dragon',
    True,
    False,
    'I would like to eat you! May I?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Ghoul',
    True,
    False,
    'I bring death to YOU!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'White Elf',
    True,
    False,
    'Mmmmmm...you seem to be ok!');

  {**Level 14 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Gooie',
    True,
    False,
    'Pssssss...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Dark Phantom',
    True,
    False,
    'Soon you will be dead!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Scorpion',
    True,
    False,
    '...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Mutant Dwarf',
    True,
    False,
    'Gnnrghh!');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Flying Vaporizer',
    True,
    False,
    'Svoosch!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Black Mage',
    True,
    False,
    'Ready to die?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Dark Knight',
    True,
    False,
    'Get ready to recieve my blows!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Thief',
    True,
    False,
    'I' + chr(39) + 'm gonna slice ya!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20, 'Wood Elf',
    True,
    False,
    'Haven' + chr(39) + 't I seen you before?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Black Scorpion',
    True,
    False, '...');

  {**Level 15 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Giant Scorpion',
    True,
    False, '...');

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Small Ape',
    True,
    False,
    'Hello! I am a monkey!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Capricorn',
    True,
    False,
    'Ihihihih!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Nightmare',
    True,
    False,
    'Uuuuuuuu!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Dark Hoodlum',
    True,
    False,
    'Cut ya! I' + chr(39) + 'm gonna cut ya!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Lurking Grudge',
    True,
    False,
    'Grrrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Cobra',
    True,
    False,
    'Ssssss..');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Troll General',
    True,
    False,
    'Gromf!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Hellcat',
    True,
    False,
    'Frssss!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Leper Woman',
    True,
    False,
    'Scheeeee!');

  {**Level 16 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Mutant Bulldog',
    True,
    False,
    'Grow! Grow! Grow!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Ogre',
    True,
    False,
    'Hum Hum! Me big, you weak!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Huge Ant',
    True,
    False, '...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Ranger',
    True,
    False,
    'Death is in the air...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Master Strangler',
    True,
    False,
    'Nice throat of yours!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Grandpa Dragon',
    True,
    False,
    'Time to toast!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Stabbing Master',
    True,
    False,
    'I would like to kill you!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    20,
    'Red Spider',
    True,
    False,
    'Nam nam! Food!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Draconian',
    True,
    False,
    'Aaaatttaaaack!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    20,
    'Elite Guard',
    True,
    False,
    'My profession is to kill people!');

  {**Level 17 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    21,
    'Orc Scoundrel',
    True,
    False,
    'Hi there! Please surrender!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    21,
    'Giant Ant',
    True,
    False, '....!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    21,
    'Rabid hound',
    True,
    False,
    'Grrrr!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    21,
    'Red Witch',
    True,
    False,
    'Hello darling!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    21,
    'Club Champion',
    True,
    False,
    'Me CHAMP! You DEAD!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    21,
    'Mad Woman',
    True,
    False,
    'Grrrr!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    21,
    'Scum of the Earth',
    True,
    False,
    'You again! Hrmmm...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    21,
    'Red Wizard',
    True,
    False,
    'God damn traitor!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    21,
    'Soldier of Fortune',
    True,
    False,
    'Good, you seem to be a suitable victim!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    21,
    'Zuul Mercenary',
    True,
    False,
    'I shall sacrifice you to my God!');

  {**Level 18 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    22,
    'Ghoul',
    True,
    False,
    'Buuu!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    22,
    'Giant Eagle',
    True,
    False,
    'Kraaaa!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    22,
    'Gnome Warrior',
    True,
    False,
    'Hehehe...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    22,
    'Baby Dront',
    True,
    False,
    'Daddy!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    22,
    'Flying Bear',
    True,
    False,
    'Grrrr...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    22,
    'Uruk-Hai',
    True,
    False,
    'Me Uruk-Hai! You are doomed!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    22,
    'Dunedain',
    True,
    False,
    'Cut the smalltalk...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    22,
    'Dream Lord',
    True,
    False,
    'Is this the REAL reality?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    22,
    'Fallguy',
    True,
    False,
    'Everbody' + chr(39) + 's on my back!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    22,
    'Renegade Troll',
    True,
    False,
    'You want my gold huh!? Come and get it!');

  {**Level 19 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    23,
    'Small Dront',
    True,
    False,
    'Aiiieee!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    23,
    'Wonder of Evil',
    True,
    False,
    'Zooming in on your brain!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    23,
    'Renegade Orc',
    True,
    False,
    'Salute your master! Punk!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    23,
    'Renegade Orc',
    True,
    False,
    'Do you have any money?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    23,
    'Hobgoblin',
    True,
    False,
    'I am quite good with my dagger...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    23,
    'Uruk-Hai',
    True,
    False,
    'Surrender or perish!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    23,
    'Sheriff',
    True,
    False,
    'You are under arrest!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    23,
    'Ghostrider',
    True,
    False,
    'Woooooaaa!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    23,
    'Mountain Tiger',
    True,
    False,
    'Grrrrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    23,
    'Mamba',
    True,
    False,
    'Ssssss...!');

  {**Level 20 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    24,
    'Hypnotic Snake',
    True,
    False,
    'Ssssssss...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    24,
    'Dragon Owl',
    True,
    False,
    'Ohohoho!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    24,
    'Huge Dront',
    True,
    False,
    'You are trouble! You must die!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    24,
    'Giant Eagle',
    True,
    False,
    'Watch your head!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    24,
    'Wizard',
    True,
    False,
    'Go to hell! Damn adventurer!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    24,
    'Orc Teenager',
    True,
    False,
    'Hihihi!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    24,
    'Orc Child',
    True,
    False,
    'Hehehe!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    24,
    'Celtic Warrior',
    True,
    False,
    'I have come far in my search!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    24,
    'Viking Leader',
    True,
    False,
    'You can' + chr(39) + 't stop me!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    24,
    'Green Dwarf',
    True,
    False,
    'Let' + chr(39) + 's have some fun!');

  {**Level 21 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Barbarian',
    True,
    False,
    'Meet my Sword!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Master Barbarian',
    True,
    False,
    'Nice weapon you have! Haha!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Renegade Elf',
    True,
    False,
    'You are pathetic! Do you know that!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Dwarf Lord',
    True,
    False,
    'Killed any Dwarves have ya!? Well, I shall stop it!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Dwarf King',
    True,
    False,
    'Screaming doesn' + chr(39) + 't help...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Bard',
    True,
    False,
    'I have a battle song for you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Thief',
    True,
    False,
    'Hi!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Gnoll',
    True,
    False,
    'Surprise!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Villain',
    True,
    False,
    'Howdy! Gimme your life!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    25,
    'Red Dwarf',
    True,
    False,
    'You look bad to me! Let' + chr(39) + 's swing the axe!');

  {**Level 22 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Shadow Knight',
    True,
    False,
    'Blow the Horn for battle!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Shadow Knight',
    True,
    False,
    'Blow the Horn for battle!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Shadow Knight',
    True,
    False,
    'Blow the Horn for battle!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Shadow Knight',
    True,
    False,
    'Blow the Horn for battle!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Shadow Knight',
    True,
    False,
    'Hi there stranger!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Shadow Knight',
    True,
    False,
    'Have yoy seen my comrades?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Shadow Knight',
    True,
    False,
    '...!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Shadow Knight',
    True,
    False,
    ' =)');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Shadow Knight',
    True,
    False,
    'Once upon a time there was...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    35,
    'Shadow Knight',
    True,
    False,
    'Have you seen my horn?');

  {**Level 23 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Gargoyle',
    True,
    False,
    'Tihihihi!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Gargoyle',
    True,
    False,
    'Tihihihi!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Gargoyle',
    True,
    False,
    'Tihihihi!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Gargoyle',
    True,
    False,
    'Tihihihi!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Gargoyle',
    True,
    False,
    'Tihihihi!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Gargoyle',
    True,
    False,
    'Tihihihi!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Gargoyle',
    True,
    False,
    'Tihihihi!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Gargoyle',
    True,
    False,
    'Tihihihi!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Gargoyle',
    True,
    False,
    'Tihihihi!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Gargoyle',
    True,
    False,
    'Tihihihi!');

  {**Level 24 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Wolfrider',
    True,
    False,
    'Grraaaahh!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Wolfrider',
    True,
    False,
    'Grraaaahh!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Wolfrider',
    True,
    False,
    'Grraaaahh!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Wolfrider',
    True,
    False,
    'Grraaaahh!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Wolfrider',
    True,
    False,
    'Grraaaahh!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Wolfrider',
    True,
    False,
    'Grraaaahh!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Wolfrider',
    True,
    False,
    'Grraaaahh!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Wolfrider',
    True,
    False,
    'Grraaaahh!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Wolfrider',
    True,
    False,
    'Grraaaahh!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    45,
    'Wolfrider',
    True,
    False,
    'Grraaaahh!');


  reset_monsters2;

  {close}
 {$I-}Close(monsterfile);{$I+}
  if IOResult <> 0 then unable_to_close(Monfile);

end;

end.
