{$IFNDEF MSDOS}
{$I DEFINES.INC}
{$ENDIF}
{

Copyright 2007 Jakob Dangarden

 This file is part of Usurper.

    Usurper is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Usurper is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Usurper; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
}

unit EdMonst2;

interface

uses
  Init, AddMonst;

procedure Reset_Monsters3;

implementation

procedure Reset_Monsters4;
begin

  {**Level 75 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    75,
    'Great Uruk-Hai',
    True,
    False,
    'Filthy scum!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    75,
    'Great Uruk-Hai',
    True,
    False,
    'Filthy scum!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    75,
    'Great Uruk-Hai',
    True,
    False,
    'Filthy scum!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    75,
    'Great Uruk-Hai',
    True,
    False,
    'Filthy scum!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    75,
    'Great Uruk-Hai',
    True,
    False,
    'Filthy scum!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    75,
    'Great Uruk-Hai',
    True,
    False,
    'Filthy scum!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    75,
    'Great Uruk-Hai',
    True,
    False,
    'Filthy scum!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    75,
    'Great Uruk-Hai',
    True,
    False,
    'Filthy scum!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    75,
    'Great Uruk-Hai',
    True,
    False,
    'Filthy scum!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    75,
    'Great Uruk-Hai',
    True,
    False,
    'Filthy scum!');

  {**Level 76 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    76,
    'Future Mercenary',
    True,
    False,
    'Are you nervous?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    76,
    'Future Mercenary',
    True,
    False,
    'Hi there!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    76,
    'Future Mercenary',
    True,
    False,
    'I am here to waste you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    76,
    'Future Mercenary',
    True,
    False,
    'Control the Universe!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    76,
    'Future Mercenary',
    True,
    False,
    'Do you belive in God?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    76,
    'Future Mercenary',
    True,
    False,
    'I must bless you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    76,
    'Future Mercenary',
    True,
    False,
    'Kneel you pagan trash!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    76,
    'Future Mercenary',
    True, False,
    'There is a prize on your head!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    76,
    'Future Mercenary',
    True,
    False,
    'I must kill, I must kill, I must...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    76,
    'Future Mercenary',
    True,
    False,
    'Pain is what you shall recieve!');

  {**Level 77 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    77,
    'Grim Barbarian',
    True,
    False,
    'So, we meet again!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    77,
    'Grim Barbarian',
    True,
    False,
    'Ah...Nay not again!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    77,
    'Grim Barbarian',
    True,
    False,
    'Who sent you? A little snack!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    77,
    'Grim Barbarian',
    True,
    False,
    'Give up now and I will spare you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    77,
    'Dwarf Mercenary',
    True,
    False,
    'Grumf! Trespasser huh!?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    77,
    'Dwarf Mercenary',
    True,
    False,
    'Grr! Here to take my gold huh!?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    77,
    'Halfling Lord',
    True,
    False,
    'Meet my friend WARHAMMER!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    77,
    'Uruk-Hai',
    True,
    False,
    'More blood to spill!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    77,
    'Uruk-Hai',
    True,
    False,
    'You are doomed!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    77,
    'Uruk-Hai',
    True,
    False,
    'Charge!!!!');

  {**Level 78 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    78,
    'Lizard Lord',
    True,
    False,
    'Ssss...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    78,
    'Lizard Lord',
    True,
    False,
    'Ssspeaking of death...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    78,
    'Lizard Lord',
    True,
    False,
    'Learn the way of the Dragon!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    78,
    'Lizard Lord',
    True,
    False,
    'Ssss...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    78,
    'Lizard Lord',
    True,
    False,
    'Mmm...another battle!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    78,
    'Lizard Lord',
    True,
    False,
    'Are you ready for me!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    78,
    'Lizard Lord',
    True,
    False,
    'Tss..Tss..Hoho!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    78,
    'Lizard Lord',
    True,
    False,
    'Let me see...You are flesh!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    78,
    'Lizard Lord',
    True,
    False,
    'Adventurers must die!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    78,
    'Lizard Lord',
    True,
    False,
    'I need food BADLY!');

  {**Level 79 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    79,
    'Dark Vibration',
    True,
    False,
    '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    79,
    'Dark Vibration',
    True,
    False,
    '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    79,
    'Dark Vibration',
    True,
    False,
    '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    79,
    'Dark Vibration',
    True,
    False,
    '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    79,
    'Dark Vibration',
    True,
    False,
    '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    79,
    'Dark Vibration',
    True,
    False,
    '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    79,
    'Dark Vibration',
    True,
    False,
    '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    79,
    'Dark Vibration',
    True,
    False,
    '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    79,
    'Dark Vibration',
    True,
    False,
    '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    79,
    'Dark Vibration',
    True,
    False,
    '...');

  {**Level 80 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    80,
    'Freak Lord',
    True,
    False,
    'Are you Insane?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    80,
    'Freak Lord',
    True,
    False,
    'Are you Sane?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    80,
    'Freak Lord',
    True,
    False,
    'I will help you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    80,
    'Freak Lord',
    True,
    False,
    'Drop your weapons!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    80,
    'Freak Lord',
    True,
    False,
    'Need a friend?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    80,
    'Freak Lord',
    True,
    False,
    'Why so hostile!?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    80,
    'Freak Lord',
    True,
    False,
    'Worship me!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    80,
    'Freak Lord',
    True,
    False,
    'Damn! I have to kill you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    80,
    'Freak Lord',
    True,
    False,
    'Say, where do you come from?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    80,
    'Freak Lord',
    True,
    False,
    'Meet my Spade!');

  {**Level 81 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    81,
    'Monster Mother',
    True,
    False,
    'Oouuuuuuu!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    81,
    'Monster Mother',
    True,
    False,
    'Oouuuuuuu!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    81,
    'Monster Mother',
    True,
    False,
    'Oouuuuuuu!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    81,
    'Monster Mother',
    True,
    False,
    'Oouuuuuuu!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    81,
    'Monster Mother',
    True,
    False,
    'Oouuuuuuu!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    81,
    'Monster Mother',
    True,
    False,
    'Oouuuuuuu!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    81,
    'Monster Mother',
    True,
    False,
    'Oouuuuuuu!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    81,
    'Monster Mother',
    True,
    False,
    'Oouuuuuuu!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    81,
    'Monster Mother',
    True,
    False,
    'Oouuuuuuu!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    81,
    'Monster Mother',
    True,
    False,
    'Oouuuuuuu!');

  {**Level 82 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    82,
    'Troll Mercenary',
    True,
    False,
    'Uruk-Hai!!!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    82,
    'Troll Mercenary',
    True,
    False,
    'Prepare to die Punk!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    82,
    'Uruk-Hai',
    True,
    False,
    'Meet my Axe!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    82,
    'Uruk-Hai',
    True,
    False,
    'I shall keep your head as a souvenir!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    82,
    'Witch King',
    True,
    False,
    'Come closer friend!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    82,
    'Witch King',
    True,
    False,
    'You make me happy!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    82,
    'Witch King',
    True,
    False,
    'Grrrrr...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    82,
    'Orc Chief',
    True,
    False,
    'Charge!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    82,
    'Orc Chief',
    True,
    False,
    'Defend yourself!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    82,
    'Orc Chief',
    True,
    False,
    'Here I come!');

  {**Level 83 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    83,
    'Animated Liquid',
    True,
    False,
    'sssss..sss..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    83,
    'Animated Liquid',
    True,
    False,
    'sssss..sss..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    83,
    'Animated Liquid',
    True,
    False,
    'sssss..sss..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    83,
    'Animated Liquid',
    True,
    False,
    'sssss..sss..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    83,
    'Animated Liquid',
    True,
    False,
    'sssss..sss..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    83,
    'Animated Liquid',
    True,
    False,
    'sssss..sss..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    83,
    'Animated Liquid',
    True,
    False,
    'sssss..sss..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    83,
    'Animated Liquid',
    True,
    False,
    'sssss..sss..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    83,
    'Animated Liquid',
    True,
    False,
    'sssss..sss..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    83,
    'Animated Liquid',
    True,
    False,
    'sssss..sss..');

  {**Level 84 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    84,
    'Purple Monster',
    True,
    False,
    'Wooiii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    84,
    'Purple Monster',
    True,
    False,
    'Wooiii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    84,
    'Purple Monster',
    True,
    False,
    'Wooiii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    84,
    'Purple Monster',
    True,
    False,
    'Wooiii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    84,
    'Purple Monster',
    True,
    False,
    'Wooiii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    84,
    'Purple Monster',
    True,
    False,
    'Wooiii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    84,
    'Purple Monster',
    True,
    False,
    'Wooiii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    84,
    'Purple Monster',
    True,
    False,
    'Wooiii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    84,
    'Purple Monster',
    True,
    False,
    'Wooiii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    84,
    'Purple Monster',
    True,
    False,
    'Wooiii...');

  {**Level 85 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    85,
    'Drug Oriented Beast',
    True,
    False,
    'Hoho...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    85,
    'Drug Oriented Beast',
    True,
    False,
    'Hoho...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    85,
    'Drug Oriented Beast',
    True,
    False,
    'Hoho...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    85,
    'Drug Oriented Beast',
    True,
    False,
    'Hoho...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    85,
    'Drug Oriented Beast',
    True,
    False,
    'Hoho...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    85,
    'Drug Oriented Beast',
    True,
    False,
    'Hoho...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    85,
    'Drug Oriented Beast',
    True,
    False,
    'Hoho...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    85,
    'Drug Oriented Beast',
    True,
    False,
    'Hoho...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    85,
    'Drug Oriented Beast',
    True,
    False,
    'Hoho...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    85,
    'Drug Oriented Beast',
    True,
    False,
    'Hoho...');

  {**Level 86 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    86,
    'Floating Mind',
    True,
    False,
    'Rrrrrr...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    86,
    'Floating Mind',
    True,
    False,
    'Rrrrrr...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    86,
    'Floating Mind',
    True,
    False,
    'Rrrrrr...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    86,
    'Floating Mind',
    True,
    False,
    'Rrrrrr...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    86,
    'Floating Mind',
    True,
    False,
    'Rrrrrr...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    86,
    'Floating Mind',
    True,
    False,
    'Rrrrrr...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    86,
    'Floating Mind',
    True,
    False,
    'Rrrrrr...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    86,
    'Floating Mind',
    True,
    False,
    'Rrrrrr...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    86,
    'Floating Mind',
    True,
    False,
    'Rrrrrr...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    86,
    'Floating Mind',
    True,
    False,
    'Rrrrrr...');

  {**Level 87 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    87,
    'Uncertain Reality',
    True,
    False,
    'Yeeeeee!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    87,
    'Uncertain Reality',
    True,
    False,
    'Yeeeeee!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    87,
    'Uncertain Reality',
    True,
    False,
    'Yeeeeee!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    87,
    'Uncertain Reality',
    True,
    False,
    'Yeeeeee!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    87,
    'Uncertain Reality',
    True,
    False,
    'Yeeeeee!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    87,
    'Uncertain Reality',
    True,
    False,
    'Yeeeeee!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    87,
    'Uncertain Reality',
    True,
    False,
    'Yeeeeee!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    87,
    'Uncertain Reality',
    True,
    False,
    'Yeeeeee!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    87,
    'Uncertain Reality',
    True,
    False,
    'Yeeeeee!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    87,
    'Uncertain Reality',
    True,
    False,
    'Yeeeeee!');

  {**Level 88 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    88,
    'Betrayer',
    True,
    False,
    'I shall put you to sleep!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    88,
    'Betrayer',
    True,
    False,
    'I shall put you to sleep!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    88,
    'Betrayer',
    True,
    False,
    'I shall put you to sleep!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    88,
    'Betrayer',
    True,
    False,
    'I shall put you to sleep!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    88,
    'Betrayer',
    True,
    False,
    'I shall put you to sleep!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    88,
    'Betrayer',
    True,
    False,
    'I shall put you to sleep!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    88,
    'Betrayer',
    True,
    False,
    'I shall put you to sleep!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    88,
    'Betrayer',
    True,
    False,
    'I shall put you to sleep!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    88,
    'Betrayer',
    True,
    False,
    'I shall put you to sleep!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    88,
    'Betrayer',
    True,
    False,
    'I shall put you to sleep!');

  {**Level 89 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    89,
    'Intruder',
    True,
    False,
    'Mmmmmm...Food!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    89,
    'Intruder',
    True,
    False,
    'Mmmmmm...Food!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    89,
    'Intruder',
    True,
    False,
    'Mmmmmm...Food!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    89,
    'Intruder',
    True,
    False,
    'Mmmmmm...Food!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    89,
    'Intruder',
    True,
    False,
    'Mmmmmm...Food!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    89,
    'Intruder',
    True,
    False,
    'Mmmmmm...Food!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    89,
    'Intruder',
    True,
    False,
    'Mmmmmm...Food!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    89,
    'Intruder',
    True,
    False,
    'Mmmmmm...Food!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    89,
    'Intruder',
    True,
    False,
    'Mmmmmm...Food!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    89,
    'Intruder',
    True,
    False,
    'Mmmmmm...Food!');

  {**Level 90 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    90,
    'Eye of Evil',
    True,
    False,
    'I see you DEAD!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    90,
    'Eye of Evil',
    True,
    False,
    'I see you DEAD!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    90,
    'Eye of Evil',
    True,
    False,
    'I see you DEAD!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    90,
    'Eye of Evil',
    True,
    False,
    'I see you DEAD!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    90,
    'Eye of Evil',
    True,
    False,
    'I see you DEAD!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    90,
    'Eye of Evil',
    True,
    False,
    'I see you DEAD!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    90,
    'Eye of Evil',
    True,
    False,
    'I see you DEAD!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    90,
    'Eye of Evil',
    True,
    False,
    'I see you DEAD!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    90,
    'Eye of Evil',
    True,
    False,
    'I see you DEAD!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    90,
    'Eye of Evil',
    True,
    False,
    'I see you DEAD!');

  {**Level 91 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    91,
    'True Antichrist',
    True,
    False,
    'Join me!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    91,
    'True Antichrist',
    True,
    False,
    'Join me!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    91,
    'True Antichrist',
    True,
    False,
    'Join me!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    91,
    'True Antichrist',
    True,
    False,
    'Join me!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    91,
    'True Antichrist',
    True,
    False,
    'Join me!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    91,
    'True Antichrist',
    True,
    False,
    'Join me!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    91,
    'True Antichrist',
    True,
    False,
    'Join me!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    91,
    'True Antichrist',
    True,
    False,
    'Join me!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    91,
    'True Antichrist',
    True,
    False,
    'Join me!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    91,
    'True Antichrist',
    True,
    False,
    'Join me!');

  {**Level 92 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    92,
    'Shadowbeast Overlord',
    True,
    False,
    'I am invincible!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    92,
    'Shadowbeast Overlord',
    True,
    False,
    'I am invincible!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    92,
    'Shadowbeast Overlord',
    True,
    False,
    'I am invincible!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    92,
    'Shadowbeast Overlord',
    True,
    False,
    'I am invincible!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    92,
    'Shadowbeast Overlord',
    True,
    False,
    'I am invincible!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    92,
    'Shadowbeast Overlord',
    True,
    False,
    'I am invincible!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    92,
    'Shadowbeast Overlord',
    True,
    False,
    'I am invincible!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    92,
    'Shadowbeast Overlord',
    True,
    False,
    'I am invincible!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    92,
    'Shadowbeast Overlord',
    True,
    False,
    'I am invincible!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    92,
    'Shadowbeast Overlord',
    True,
    False,
    'I am invincible!');

  {**Level 93 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    93,
    'Lurking Horror',
    True,
    False,
    'Grrr! Grrr! Grrr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    93,
    'Lurking Horror',
    True,
    False,
    'Grrr! Grrr! Grrr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    93,
    'Lurking Horror',
    True,
    False,
    'Grrr! Grrr! Grrr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    93,
    'Lurking Horror',
    True,
    False,
    'Grrr! Grrr! Grrr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    93,
    'Lurking Horror',
    True,
    False,
    'Grrr! Grrr! Grrr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    93,
    'Lurking Horror',
    True,
    False,
    'Grrr! Grrr! Grrr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    93,
    'Lurking Horror',
    True,
    False,
    'Grrr! Grrr! Grrr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    93,
    'Lurking Horror',
    True,
    False,
    'Grrr! Grrr! Grrr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    93,
    'Lurking Horror',
    True,
    False,
    'Grrr! Grrr! Grrr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    93,
    'Lurking Horror',
    True,
    False,
    'Grrr! Grrr! Grrr!');

  {**Level 94 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    94,
    'Salamander from Hell',
    True,
    False,
    'Gnnggg!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    94,
    'Salamander from Hell',
    True,
    False,
    'Gnnggg!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    94,
    'Salamander from Hell',
    True,
    False,
    'Gnnggg!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    94,
    'Salamander from Hell',
    True,
    False,
    'Gnnggg!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    94,
    'Salamander from Hell',
    True,
    False,
    'Gnnggg!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    94,
    'Salamander from Hell',
    True,
    False,
    'Gnnggg!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    94,
    'Salamander from Hell',
    True,
    False,
    'Gnnggg!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    94,
    'Salamander from Hell',
    True,
    False,
    'Gnnggg!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    94,
    'Salamander from Hell',
    True,
    False,
    'Gnnggg!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    94,
    'Salamander from Hell',
    True,
    False,
    'Gnnggg!');

  {**Level 95 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    95,
    'Vulture Lord',
    True,
    False,
    'Waaaa!!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    95,
    'Giant Vulture',
    True,
    False,
    'Waaaa!!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    95,
    'Supreme Vulture',
    True,
    False,
    'Waaaa!!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    95,
    'Red Vulture',
    True,
    False,
    'Waaaa!!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    95,
    'Dragon Vulture',
    True,
    False,
    'Waaaa!!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    95,
    'Saurons Pet',
    True,
    False,
    'Waaaa!!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    95,
    'Mad Vulture',
    True,
    False,
    'Waaaa!!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    95,
    'Dark Vulture',
    True,
    False,
    'Waaaa!!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    95,
    'Black Vulture',
    True,
    False,
    'Waaaa!!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    95,
    'Evil Vulture',
    True,
    False,
    'Waaaa!!');

  {**Level 96 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    96,
    'Shadow Prince',
    True,
    False,
    'Ohh! What have we here!?');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    96,
    'Shadow Prince',
    True,
    False,
    'You are to die...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    96,
    'Shadow Prince',
    True,
    False,
    'I have come to rule the world!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    96,
    'Shadow Prince',
    True,
    False,
    'Kneel before your master!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    96,
    'Shadow Prince',
    True,
    False,
    'I like dead adventurers!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    96,
    'Shadow Prince',
    True,
    False,
    'You look like a bag of dirt!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    96,
    'Shadow Prince',
    True,
    False,
    'You do not know of my powers!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    96,
    'Shadow Prince',
    True,
    False,
    'You have choosen the wrong opponent!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    96,
    'Shadow Prince',
    True,
    False,
    'Lick my boots! Serf!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    96,
    'Shadow Prince',
    True,
    False,
    'A nice day for a kill!');

  {**Level 97 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    97,
    'Nameless Horror',
    True,
    False,
    'Ooooooooo...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    97,
    'Nameless Horror',
    True,
    False,
    'Ooooooooo...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    97,
    'Nameless Horror',
    True,
    False,
    'Ooooooooo...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    97,
    'Nameless Horror',
    True,
    False,
    'Ooooooooo...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    97,
    'Nameless Horror',
    True,
    False,
    'Ooooooooo...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    97,
    'Nameless Horror',
    True,
    False,
    'Ooooooooo...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    97,
    'Nameless Horror',
    True,
    False,
    'Ooooooooo...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    97,
    'Nameless Horror',
    True,
    False,
    'Ooooooooo...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    97,
    'Nameless Horror',
    True,
    False,
    'Ooooooooo...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    97,
    'Nameless Horror',
    True,
    False,
    'Ooooooooo...');

  {**Level 98 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    98,
    'Nazgul Lord',
    True,
    False,
    'Feel my wrath!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    98,
    'Nazgul',
    True,
    False,
    'You cannot win this war!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    98,
    'Nazgul',
    True,
    False,
    'Taste my sword!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    98,
    'Nazgul',
    True,
    False,
    'This will be a slaughter!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    98,
    'Nazgul',
    True,
    False,
    'Kiss this world goodbye!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    98,
    'Nazgul',
    True,
    False,
    'Long live Evil!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    98,
    'Nazgul',
    True,
    False,
    'You have not seen the light!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    98,
    'Nazgul',
    True,
    False,
    'Face your defeat! Join us!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    98,
    'Nazgul',
    True,
    False,
    'I hope that you are ready...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    98,
    'Nazgul',
    True,
    False,
    'You against me!? Hahaha!');

  {**Level 99 monsters **}

  add_monster(True,                     { Armoruser }
    False,
    0,
    0,
    99,
    'Supreme Dragon',
    True,
    False,
    'Mmmm...hoho...!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    99,
    'Dragon Lord',
    True,
    False,
    'Come closer friend!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    99,
    'Mountain Dragon',
    True,
    False,
    'Wanna rip me off huh!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    99,
    'Black Dragon',
    True,
    False,
    'Feel my breath fool!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    99,
    'Screaming Dragon',
    True,
    False,
    'Who are you to challenge ME!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    99,
    'Dark Dragon',
    True,
    False,
    'Ahhh...Another victim!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    99,
    'Evil Dragon',
    True,
    False,
    'Ssssssleeeep!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    99,
    'Dargoths Dragon',
    True,
    False,
    'Grmmmm...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    99,
    'Dragon of Doom',
    True,
    False,
    'I am your destiny!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    99,
    'Ultimate Dragon',
    True,
    False,
    'Watch me!');

  {**Level 100 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    100,
    'Balrog Lord',
    True,
    False,
    'Gnnn...!!!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    100,
    'Balrog Master',
    True,
    False,
    'You have come far!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    100,
    'Giant Balrog',
    True,
    False,
    'Turn back pagan!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    100,
    'Mutant Balrog',
    True,
    False,
    'And I have waited!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    100,
    'Ring Balrog',
    True,
    False,
    'There can only be one!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    100,
    'Supreme Balrog',
    True,
    False,
    'Mmmm...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    100,
    'Hideous Balrog',
    True,
    False,
    'Grrr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    100,
    'Hells Balrog',
    True,
    False,
    'Are you afraid? You should be...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    100,
    'Black Balrog',
    True,
    False,
    'I am disappointed! You look like a little insect!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    100,
    'Balrog of Doom',
    True,
    False,
    'You look like something that just wants to be killed!');

  {**Level 101 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    150,
    'Supreme Being',
    True,
    False, '...');

end;

procedure Reset_Monsters3;
begin

  {**Level 50 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    50,
    'Creeping Death',
    True,
    False,
    'Ohhhii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    50,
    'Creeping Death',
    True,
    False,
    'Ohhhii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    50,
    'Creeping Death',
    True,
    False,
    'Ohhhii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    50,
    'Creeping Death',
    True,
    False,
    'Ohhhii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    50,
    'Creeping Death',
    True,
    False,
    'Ohhhii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    50,
    'Creeping Death',
    True,
    False,
    'Ohhhii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    50,
    'Creeping Death',
    True,
    False,
    'Ohhhii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    50,
    'Creeping Death',
    True,
    False,
    'Ohhhii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    50,
    'Creeping Death',
    True,
    False,
    'Ohhhii...');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    50,
    'Creeping Death',
    True,
    False,
    'Ohhhii...');

  {**Level 51 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    51,
    'Murdering Beast',
    True,
    False,
    'Grunt..Grunt..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    51,
    'Murdering Beast',
    True,
    False,
    'Grunt..Grunt..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    51,
    'Murdering Beast',
    True,
    False,
    'Grunt..Grunt..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    51,
    'Murdering Beast',
    True,
    False,
    'Grunt..Grunt..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    51,
    'Murdering Beast',
    True,
    False,
    'Grunt..Grunt..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    51,
    'Murdering Beast',
    True,
    False,
    'Grunt..Grunt..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    51,
    'Murdering Beast',
    True,
    False,
    'Grunt..Grunt..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    51,
    'Murdering Beast',
    True,
    False,
    'Grunt..Grunt..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    51,
    'Murdering Beast',
    True,
    False,
    'Grunt..Grunt..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    51,
    'Murdering Beast',
    True,
    False,
    'Grunt..Grunt..');

  {**Level 52 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    52,
    'Big Bad Wolf',
    True,
    False,
    'Hehe..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    52,
    'Big Bad Wolf',
    True,
    False,
    'Hehe..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    52,
    'Big Bad Wolf',
    True,
    False,
    'Hehe..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    52,
    'Big Bad Wolf',
    True,
    False,
    'Hehe..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    52,
    'Big Bad Wolf',
    True,
    False,
    'Hehe..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    52,
    'Big Bad Wolf',
    True,
    False,
    'Hehe..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    52,
    'Big Bad Wolf',
    True,
    False,
    'Hehe..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    52,
    'Big Bad Wolf',
    True,
    False,
    'Hehe..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    52,
    'Big Bad Wolf',
    True,
    False,
    'Hehe..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    52,
    'Big Bad Wolf',
    True,
    False,
    'Hehe..');

  {**Level 53 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    53,
    'Well Monster',
    True,
    False,
    'Psss..');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    53,
    'Well Monster',
    True,
    False,
    'Psss..');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    53,
    'Well Monster',
    True,
    False,
    'Psss..');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    53,
    'Well Monster',
    True,
    False,
    'Psss..');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    53,
    'Well Monster',
    True,
    False,
    'Psss..');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    53,
    'Well Monster',
    True,
    False,
    'Psss..');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    53,
    'Well Monster',
    True,
    False,
    'Psss..');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    53,
    'Well Monster',
    True,
    False,
    'Psss..');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    53,
    'Well Monster',
    True,
    False,
    'Psss..');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    53,
    'Well Monster',
    True,
    False,
    'Psss..');

  {**Level 54 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    54,
    'Troll Wizard',
    True,
    False,
    'Grouu!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    54,
    'Troll Wizard',
    True,
    False,
    'Grouu!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    54,
    'Troll Wizard',
    True,
    False,
    'Grouu!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    54,
    'Troll Wizard',
    True,
    False,
    'Grouu!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    54,
    'Troll Wizard',
    True,
    False,
    'Grouu!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    54,
    'Troll Wizard',
    True,
    False,
    'Grouu!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    54,
    'Troll Wizard',
    True,
    False,
    'Grouu!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    54,
    'Troll Wizard',
    True,
    False,
    'Grouu!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    54,
    'Troll Wizard',
    True,
    False,
    'Grouu!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    54,
    'Troll Wizard',
    True,
    False,
    'Grouu!');

  {**Level 55 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    55,
    'Physical Nightmare',
    True,
    False,
    'Zzzzzz...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    55,
    'Physical Nightmare',
    True,
    False,
    'Zzzzzz...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    55,
    'Physical Nightmare',
    True,
    False,
    'Zzzzzz...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    55,
    'Physical Nightmare',
    True,
    False,
    'Zzzzzz...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    55,
    'Physical Nightmare',
    True,
    False,
    'Zzzzzz...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    55,
    'Physical Nightmare',
    True,
    False,
    'Zzzzzz...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    55,
    'Physical Nightmare',
    True,
    False,
    'Zzzzzz...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    55,
    'Physical Nightmare',
    True,
    False,
    'Zzzzzz...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    55,
    'Physical Nightmare',
    True,
    False,
    'Zzzzzz...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    55,
    'Physical Nightmare',
    True,
    False,
    'Zzzzzz...');

  {**Level 56 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    56,
    'Supreme Assassin',
    True,
    False,
    'I shall deliver you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    56,
    'Supreme Assassin',
    True,
    False,
    'I shall deliver you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    56,
    'Supreme Assassin',
    True,
    False,
    'I shall deliver you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    56,
    'Supreme Assassin',
    True,
    False,
    'I shall deliver you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    56,
    'Supreme Assassin',
    True,
    False,
    'I shall deliver you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    56,
    'Supreme Assassin',
    True,
    False,
    'I shall deliver you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    56,
    'Supreme Assassin',
    True,
    False,
    'I shall deliver you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    56,
    'Supreme Assassin',
    True,
    False,
    'I shall deliver you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    56,
    'Supreme Assassin',
    True,
    False,
    'I shall deliver you!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    56,
    'Supreme Assassin',
    True,
    False,
    'I shall deliver you!');

  {**Level 57 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    57,
    'Teacher of Death',
    True,
    False,
    'Another visitor! Stay a while!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    57,
    'Teacher of Death',
    True,
    False,
    'Another visitor! Stay a while!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    57,
    'Teacher of Death',
    True,
    False,
    'Another visitor! Stay a while!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    57,
    'Teacher of Death',
    True,
    False,
    'Another visitor! Stay a while!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    57,
    'Teacher of Death',
    True,
    False,
    'Another visitor! Stay a while!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    57,
    'Teacher of Death',
    True,
    False,
    'Another visitor! Stay a while!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    57,
    'Teacher of Death',
    True,
    False,
    'Another visitor! Stay a while!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    57,
    'Teacher of Death',
    True,
    False,
    'Another visitor! Stay a while!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    57,
    'Teacher of Death',
    True,
    False,
    'Another visitor! Stay a while!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    57,
    'Teacher of Death',
    True,
    False,
    'Another visitor! Stay a while!');

  {**Level 58 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    58,
    'Dominator',
    True,
    False,
    'I need to practice...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    58,
    'Dominator',
    True,
    False,
    'I need to practice...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    58,
    'Dominator',
    True,
    False,
    'I need to practice...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    58,
    'Dominator',
    True,
    False,
    'I need to practice...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    58,
    'Dominator',
    True,
    False,
    'I need to practice...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    58,
    'Dominator',
    True,
    False,
    'I need to practice...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    58,
    'Dominator',
    True,
    False,
    'I need to practice...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    58,
    'Dominator',
    True,
    False,
    'I need to practice...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    58,
    'Dominator',
    True,
    False,
    'I need to practice...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    58,
    'Dominator',
    True,
    False,
    'I need to practice...');

  {**Level 59 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    59,
    'Witchdoctor',
    True,
    False,
    'Asghal Masghal Nizpo Wahr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    59,
    'Witchdoctor',
    True,
    False,
    'Asghal Masghal Nizpo Wahr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    59,
    'Witchdoctor',
    True,
    False,
    'Asghal Masghal Nizpo Wahr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    59,
    'Witchdoctor',
    True,
    False,
    'Asghal Masghal Nizpo Wahr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    59,
    'Witchdoctor',
    True,
    False,
    'Asghal Masghal Nizpo Wahr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    59,
    'Witchdoctor',
    True,
    False,
    'Asghal Masghal Nizpo Wahr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    59,
    'Witchdoctor',
    True,
    False,
    'Asghal Masghal Nizpo Wahr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    59,
    'Witchdoctor',
    True,
    False,
    'Asghal Masghal Nizpo Wahr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    59,
    'Witchdoctor',
    True,
    False,
    'Asghal Masghal Nizpo Wahr!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    59,
    'Witchdoctor',
    True,
    False,
    'Asghal Masghal Nizpo Wahr!');

  {**Level 60 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    60,
    'Ghoul Lord',
    True,
    False,
    'The winds are true...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    60,
    'Ghoul Lord',
    True,
    False,
    'The winds are true...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    60,
    'Ghoul Lord',
    True,
    False,
    'The winds are true...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    60,
    'Ghoul Lord',
    True,
    False,
    'The winds are true...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    60,
    'Ghoul Lord',
    True,
    False,
    'The winds are true...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    60,
    'Ghoul Lord',
    True,
    False,
    'The winds are true...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    60,
    'Ghoul Lord',
    True,
    False,
    'The winds are true...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    60,
    'Ghoul Lord',
    True,
    False,
    'The winds are true...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    60,
    'Ghoul Lord',
    True,
    False,
    'The winds are true...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    60,
    'Ghoul Lord',
    True,
    False,
    'The winds are true...');

  {**Level 61 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    61,
    'Red Tiger',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    61,
    'Red Tiger',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    61,
    'Red Tiger',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    61,
    'Red Tiger',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    61,
    'Red Tiger',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    61,
    'Red Tiger',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    61,
    'Red Tiger',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    61,
    'Red Tiger',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    61,
    'Red Tiger',
    True,
    False,
    'Grrrrr!');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    61,
    'Red Tiger',
    True,
    False,
    'Grrrrr!');

  {**Level 62 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    62,
    'Berzerk from Hell',
    True,
    False,
    'Run, run while you still can...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    62,
    'Berzerk from Hell',
    True,
    False,
    'Run, run while you still can...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    62,
    'Berzerk from Hell',
    True,
    False,
    'Run, run while you still can...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    62,
    'Berzerk from Hell',
    True,
    False,
    'Run, run while you still can...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    62,
    'Berzerk from Hell',
    True,
    False,
    'Run, run while you still can...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    62,
    'Berzerk from Hell',
    True,
    False,
    'Run, run while you still can...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    62,
    'Berzerk from Hell',
    True,
    False,
    'Run, run while you still can...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    62,
    'Berzerk from Hell',
    True,
    False,
    'Run, run while you still can...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    62,
    'Berzerk from Hell',
    True,
    False,
    'Run, run while you still can...');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    62,
    'Berzerk from Hell',
    True,
    False,
    'Run, run while you still can...');

  {**Level 63 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    63,
    'Phantasy Lord',
    True,
    False,
    'You are not worth dealing with!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    63,
    'Phantasy Lord',
    True,
    False,
    'You are not wort dealing with!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    63,
    'Phantasy Lord',
    True,
    False,
    'You are not worth dealing with!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    63,
    'Phantasy Lord',
    True,
    False,
    'You are not worth dealing with!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    63,
    'Phantasy Lord',
    True,
    False,
    'You are not worth dealing with!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    63,
    'Phantasy Lord',
    True,
    False,
    'You are not worth dealing with!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    63,
    'Phantasy Lord',
    True,
    False,
    'You are not worth dealing with!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    63,
    'Phantasy Lord',
    True,
    False,
    'You are not worth dealing with!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    63,
    'Phantasy Lord',
    True,
    False,
    'You are not worth dealing with!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    63,
    'Phantasy Lord',
    True,
    False,
    'You are not worth dealing with!');

  {**Level 64 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    64,
    'Ruthless Mage',
    True,
    False,
    'Hello, dear friend!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    64,
    'Ruthless Mage',
    True,
    False,
    'Hello, dear friend!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    64,
    'Ruthless Mage',
    True,
    False,
    'Hello, dear friend!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    64,
    'Ruthless Mage',
    True,
    False,
    'Hello, dear friend!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    64,
    'Ruthless Mage',
    True,
    False,
    'Hello, dear friend!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    64,
    'Ruthless Mage',
    True,
    False,
    'Hello, dear friend!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    64,
    'Ruthless Mage',
    True,
    False,
    'Hello, dear friend!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    64,
    'Ruthless Mage',
    True,
    False,
    'Hello, dear friend!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    64,
    'Ruthless Mage',
    True,
    False,
    'Hello, dear friend!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    64,
    'Ruthless Mage',
    True,
    False,
    'Hello, dear friend!');

  {**Level 65 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    65,
    'Disturbed Sense',
    True,
    False,
    'Zuuuuhhh...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    65,
    'Disturbed Sense',
    True,
    False,
    'Zuuuuhhh...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    65,
    'Disturbed Sense',
    True,
    False,
    'Zuuuuhhh...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    65,
    'Disturbed Sense',
    True,
    False,
    'Zuuuuhhh...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    65,
    'Disturbed Sense',
    True,
    False,
    'Zuuuuhhh...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    65,
    'Disturbed Sense',
    True,
    False,
    'Zuuuuhhh...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    65,
    'Disturbed Sense',
    True,
    False,
    'Zuuuuhhh...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    65,
    'Disturbed Sense',
    True,
    False,
    'Zuuuuhhh...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    65,
    'Disturbed Sense',
    True,
    False,
    'Zuuuuhhh...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    65,
    'Disturbed Sense',
    True,
    False,
    'Zuuuuhhh...');

  {**Level 66 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    66,
    'Mind Corruptor',
    True,
    False,
    'Ihhhhh..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    66,
    'Mind Corruptor',
    True,
    False,
    'Ihhhhh..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    66,
    'Mind Corruptor',
    True,
    False,
    'Ihhhhh..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    66,
    'Mind Corruptor',
    True,
    False,
    'Ihhhhh..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    66,
    'Mind Corruptor',
    True,
    False,
    'Ihhhhh..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    66,
    'Mind Corruptor',
    True,
    False,
    'Ihhhhh..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    66,
    'Mind Corruptor',
    True,
    False,
    'Ihhhhh..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    66,
    'Mind Corruptor',
    True,
    False,
    'Ihhhhh..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    66,
    'Mind Corruptor',
    True,
    False,
    'Ihhhhh..');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    66,
    'Mind Corruptor',
    True,
    False,
    'Ihhhhh..');

  {**Level 67 monsters **}

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    67,
    'Senior Thug',
    True,
    False,
    'I am your fate!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    67,
    'Senior Thug',
    True,
    False,
    'I am your fate!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    67,
    'Senior Thug',
    True,
    False,
    'I am your fate!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    67,
    'Senior Thug',
    True,
    False,
    'I am your fate!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    67,
    'Senior Thug',
    True,
    False,
    'I am your fate!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    67,
    'Senior Thug',
    True,
    False,
    'I am your fate!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    67,
    'Senior Thug',
    True,
    False,
    'I am your fate!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    67,
    'Senior Thug',
    True,
    False,
    'I am your fate!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    67,
    'Senior Thug',
    True,
    False,
    'I am your fate!');

  add_monster(True,                     { Armoruser }
    True,
    0,
    0,
    67,
    'Senior Thug',
    True,
    False,
    'I am your fate!');

  {**Level 68 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    68,
    'Mind Bender',
    True,
    False,
    'Humhumhumhumhum!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    68,
    'Mind Bender',
    True,
    False,
    'Humhumhumhumhum!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    68,
    'Mind Bender',
    True,
    False,
    'Humhumhumhumhum!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    68,
    'Mind Bender',
    True,
    False,
    'Humhumhumhumhum!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    68,
    'Mind Bender',
    True,
    False,
    'Humhumhumhumhum!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    68,
    'Mind Bender',
    True,
    False,
    'Humhumhumhumhum!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    68,
    'Mind Bender',
    True,
    False,
    'Humhumhumhumhum!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    68,
    'Mind Bender',
    True,
    False,
    'Humhumhumhumhum!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    68,
    'Mind Bender',
    True,
    False,
    'Humhumhumhumhum!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    68,
    'Mind Bender',
    True,
    False,
    'Humhumhumhumhum!');

  {**Level 69 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    69,
    'Animated Fear',
    True,
    False,
    'Sssssss...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    69,
    'Animated Fear',
    True,
    False,
    'Sssssss...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    69,
    'Animated Fear',
    True,
    False,
    'Sssssss...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    69,
    'Animated Fear',
    True,
    False,
    'Sssssss...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    69,
    'Animated Fear',
    True,
    False,
    'Sssssss...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    69,
    'Animated Fear',
    True,
    False,
    'Sssssss...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    69,
    'Animated Fear',
    True,
    False,
    'Sssssss...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    69,
    'Animated Fear',
    True,
    False,
    'Sssssss...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    69,
    'Animated Fear',
    True,
    False,
    'Sssssss...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    69,
    'Animated Fear',
    True,
    False,
    'Sssssss...');

  {**Level 70 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    70,
    'Life Distinguisher',
    True,
    False,
    'Oh! Another customer!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    70,
    'Life Distinguisher',
    True,
    False,
    'Oh! Another customer!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    70,
    'Life Distinguisher',
    True,
    False,
    'Oh! Another customer!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    70,
    'Life Distinguisher',
    True,
    False,
    'Oh! Another customer!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    70,
    'Life Distinguisher',
    True,
    False,
    'Oh! Another customer!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    70,
    'Life Distinguisher',
    True,
    False,
    'Oh! Another customer!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    70,
    'Life Distinguisher',
    True,
    False,
    'Oh! Another customer!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    70,
    'Life Distinguisher',
    True,
    False,
    'Oh! Another customer!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    70,
    'Life Distinguisher',
    True,
    False,
    'Oh! Another customer!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    70,
    'Life Distinguisher',
    True,
    False,
    'Oh! Another customer!');

  {**Level 71 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    71,
    'Pain Sequel',
    True,
    False,
    'Gooorgh!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    71,
    'Pain Sequel',
    True,
    False,
    'Gooorgh!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    71,
    'Pain Sequel',
    True,
    False,
    'Gooorgh!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    71,
    'Pain Sequel',
    True,
    False,
    'Gooorgh!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    71,
    'Pain Sequel',
    True,
    False,
    'Gooorgh!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    71,
    'Pain Sequel',
    True,
    False,
    'Gooorgh!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    71,
    'Pain Sequel',
    True,
    False,
    'Gooorgh!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    71,
    'Pain Sequel',
    True,
    False,
    'Gooorgh!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    71,
    'Pain Sequel',
    True,
    False,
    'Gooorgh!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    71,
    'Pain Sequel',
    True,
    False,
    'Gooorgh!');

  {**Level 72 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    72,
    'Blob',
    True,
    False,
    'Momph!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    72,
    'Blob',
    True,
    False,
    'Momph!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    72,
    'Blob',
    True,
    False,
    'Momph!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    72,
    'Blob',
    True,
    False,
    'Momph!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    72,
    'Blob',
    True,
    False,
    'Momph!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    72,
    'Blob',
    True,
    False,
    'Momph!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    72,
    'Blob',
    True,
    False,
    'Momph!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    72,
    'Blob',
    True,
    False,
    'Momph!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    72,
    'Blob',
    True,
    False,
    'Momph!?');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    72,
    'Blob',
    True,
    False,
    'Momph!?');

  {**Level 73 monsters **}

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    73,
    'Tripper',
    True,
    False,
    'I have just decided to kill You!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    73,
    'Tripper',
    True,
    False,
    'I have just decided to kill You!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    73,
    'Tripper',
    True,
    False,
    'I have just decided to kill You!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    73,
    'Tripper',
    True,
    False,
    'I have just decided to kill You!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    73,
    'Tripper',
    True,
    False,
    'I have just decided to kill You!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    73,
    'Tripper',
    True,
    False,
    'I have just decided to kill You!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    73,
    'Tripper',
    True,
    False,
    'I have just decided to kill You!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    73,
    'Tripper',
    True,
    False,
    'I have just decided to kill You!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    73,
    'Tripper',
    True,
    False,
    'I have just decided to kill You!');

  add_monster(False,                     { Armoruser }
    True,
    0,
    0,
    73,
    'Tripper',
    True,
    False,
    'I have just decided to kill You!');

  {**Level 74 monsters **}

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    74,
    'Gongong',
    True,
    False, '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    74,
    'Gongong',
    True,
    False, '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    74,
    'Gongong',
    True,
    False, '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    74,
    'Gongong',
    True,
    False, '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    74,
    'Gongong',
    True,
    False, '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    74,
    'Gongong',
    True,
    False, '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    74,
    'Gongong',
    True,
    False, '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    74,
    'Gongong',
    True,
    False, '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    74,
    'Gongong',
    True,
    False, '...');

  add_monster(False,                     { Armoruser }
    False,
    0,
    0,
    74,
    'Gongong',
    True,
    False, '...');

  reset_monsters4;

end;

end.
