{$IFNDEF MSDOS}
{$I DEFINES.INC}
{$ENDIF}
{

Copyright 2007 Jakob Dangarden

 This file is part of Usurper.

    Usurper is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Usurper is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Usurper; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
}

Unit EdWeap2;

Interface
uses init, Obj_Ad, Edweap3;


procedure Reset_weapons2;

implementation

procedure Reset_weapons2;
begin

  Add_Object('Neros Sword',   {name}
            Weapon,    {typ}
            860000,    {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            91,        {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Guardians Axe',   {name}
            Weapon,    {typ}
            890000,    {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            92,        {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Morgoths Bow',   {name}
            Weapon,    {typ}
            900000,    {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            93,        {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Ganeshas Pole',   {name}
            Weapon,    {typ}
            910000,    {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            94,        {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Bow of Gaoh',   {name}
            Weapon,    {typ}
            930000,    {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            95,        {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Poisoned Bow',   {name}
            Weapon,    {typ}
            940000,    {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            96,        {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Gborogboros Staff',   {name}
            Weapon,    {typ}
            960000,    {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            97,        {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Geryons Sword',   {name}
            Weapon,    {typ}
            980000,    {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            98,        {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Garudas Axe',   {name}
            Weapon,    {typ}
            1000000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            99,        {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('GrimAxe',   {name}
            Weapon,    {typ}
            1250000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            100,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Garangas Lance',   {name}
            Weapon,    {typ}
            1400000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            101,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Whisper of Satan',   {name}
            Weapon,    {typ}
            1500000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            102,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Gilgamesh Sword',   {name}
            Weapon,    {typ}
            1700000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            103,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Demon Sword',   {name}
            Weapon,    {typ}
            2000000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            104,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Club of Ja',   {name}
            Weapon,    {typ}
            2200000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            105,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Gong-Gongs Horn',   {name}
            Weapon,    {typ}
            2400000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            106,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',       {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Guan Dis Spear',   {name}
            Weapon,    {typ}
            2600000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            107,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Grainnes Dagger',   {name}
            Weapon,    {typ}
            2800000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            108,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Claws of IT',   {name}
            Weapon,    {typ}
            3000000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            109,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Grendel Slayer',   {name}
            Weapon,    {typ}
            3200000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            110,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('The Force',   {name}
            Weapon,    {typ}
            3500000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            111,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Gylfes Weapon',   {name}
            Weapon,    {typ}
            3700000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            112,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Axe of Destruction',   {name}
            Weapon,    {typ}
            4000000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            113,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Hachimans Pole',   {name}
            Weapon,    {typ}
            4200000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            114,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Death Dagger',   {name}
            Weapon,    {typ}
            4400000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            115,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Claws of Draki',   {name}
            Weapon,    {typ}
            4600000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            116,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Claws of Muffi',   {name}
            Weapon,    {typ}
            5000000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            117,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Hectors WarAxe',   {name}
            Weapon,    {typ}
            6000000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            118,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Heimdalls Sword',   {name}
            Weapon,    {typ}
            6500000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            119,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Heimdalls Horn',   {name}
            Weapon,    {typ}
            7000000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            120,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Sun Dagger',   {name}
            Weapon,    {typ}
            7200000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            121,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Floating Club',   {name}
            Weapon,    {typ}
            7400000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            122,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Hengists Hammer',   {name}
            Weapon,    {typ}
            7600000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            123,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Heras Lance',   {name}
            Weapon,    {typ}
            7900000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            124,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Herakles Lance',   {name}
            Weapon,    {typ}
            8400000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            125,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Imsets Dagger',   {name}
            Weapon,    {typ}
            8600000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            126,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Hengists Sword',   {name}
            Weapon,    {typ}
            8700000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            127,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Hermes Warhammer',   {name}
            Weapon,    {typ}
            9000000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            128,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Inaris Knife',   {name}
            Weapon,    {typ}
            9300000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            129,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Horus Club',   {name}
            Weapon,    {typ}
            9500000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            130,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Dancing Dagger',   {name}
            Weapon,    {typ}
            9600000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            131,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Claws of Hipppolyt',   {name}
            Weapon,    {typ}
            9700000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            132,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Demonblade',   {name}
            Weapon,    {typ}
            9900000,   {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            133,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('White Sword',   {name}
            Weapon,    {typ}
            10000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            134,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Absolyms Club',   {name}
            Weapon,    {typ}
            13000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            135,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Hyakinthos Secret Weapon',   {name}
            Weapon,    {typ}
            15000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            136,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Hypnose Dagger',   {name}
            Weapon,    {typ}
            16000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            137,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Lords Gift',   {name}
            Weapon,    {typ}
            17000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            138,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Holy Lance',   {name}
            Weapon,    {typ}
            20000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            139,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Holy Dagger',   {name}
            Weapon,    {typ}
            23000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            140,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Demon Reaper',   {name}
            Weapon,    {typ}
            25000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            141,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Skeletons Hand',   {name}
            Weapon,    {typ}
            27000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            142,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Evil Sword',   {name}
            Weapon,    {typ}
            30000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            143,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Holy Sword',   {name}
            Weapon,    {typ}
            32000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            144,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Devils Axe',   {name}
            Weapon,    {typ}
            35000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            145,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Staff of Gondolin',   {name}
            Weapon,    {typ}
            36000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            146,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Ymers Broadsword',   {name}
            Weapon,    {typ}
            37000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            147,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Gloins Hammer',   {name}
            Weapon,    {typ}
            38000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            148,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Eomers Sword',   {name}
            Weapon,    {typ}
            39000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            149,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Sling of Darkness',   {name}
            Weapon,    {typ}
            40000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            150,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Bregalads Bow',   {name}
            Weapon,    {typ}
            41000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            151,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Dagger of Morgul',   {name}
            Weapon,    {typ}
            42000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            152,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Troll Dagger',   {name}
            Weapon,    {typ}
            43000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            153,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Elrohirs Blade',   {name}
            Weapon,    {typ}
            44000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            154,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Blood Sword',   {name}
            Weapon,    {typ}
            45000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            155,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Elladans Lance',   {name}
            Weapon,    {typ}
            46000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            156,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Dark Axe',   {name}
            Weapon,    {typ}
            47000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            157,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Khazad Bow',   {name}
            Weapon,    {typ}
            48000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            158,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Mellons Staff',   {name}
            Weapon,    {typ}
            49000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            159,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Horn of the Past',   {name}
            Weapon,    {typ}
            50000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            160,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Horn of Gondolin',   {name}
            Weapon,    {typ}
            51000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            161,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Axe of Durin',   {name}
            Weapon,    {typ}
            52000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            162,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Balins Blade',   {name}
            Weapon,    {typ}
            53000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            163,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Mazarbuls Club',   {name}
            Weapon,    {typ}
            54000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            164,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Dront Bow',   {name}
            Weapon,    {typ}
            55000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            165,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Sword of the Undead',   {name}
            Weapon,    {typ}
            56000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            166,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Scorpio Sword',   {name}
            Weapon,    {typ}
            57000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            167,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Scorpio Axe',   {name}
            Weapon,    {typ}
            58000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            168,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Hammer of War',   {name}
            Weapon,    {typ}
            59000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            169,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('White Hammer',   {name}
            Weapon,    {typ}
            60000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            170,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Boromirs Sword',   {name}
            Weapon,    {typ}
            61000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            171,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('DragonBane',   {name}
            Weapon,    {typ}
            62000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            172,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Sword of Exodus',   {name}
            Weapon,    {typ}
            63000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            173,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Muromets Staff',   {name}
            Weapon,    {typ}
            65000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            174,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Dancing Pole',   {name}
            Weapon,    {typ}
            70000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            175,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Ikaros Staff',   {name}
            Weapon,    {typ}
            75000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            176,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Sword of Legend',   {name}
            Weapon,    {typ}
            80000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            177,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Hammer of Baal',   {name}
            Weapon,    {typ}
            85000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            178,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}

  Add_Object('Exploding Sword',   {name}
            Weapon,    {typ}
            90000000,  {v„rde i gold}
            0,         {”ka/minska hps}
            0,         {”ka stamina}
            0,         {”ka agility}
            0,         {”ka charisma}
            0,         {”ka dexterity}
            0,         {”ka wisdom}
            0,         {”ka mana}
            0,         {”ka armor v„rde}
            179,       {”ka attack v„rde}
            '',        {„gd av?}
            False,     {bara EN i spelet}
            Nothing, {kurerar}
            True,      {finnas i shoppen}
            False,     {kunna hittas i dungeons?}
            False,     {cursed item?}
            1,         {min level att hittas i dngs}
            99,        {max level att hittas i dngs}
            'You see nothing special.',
            '',        {normal beskrivning 2}
            '',        {normal beskrivning 3}
            '',        {normal beskrivning 4}
            '',        {normal beskrivning 5}
            '',        {detaljerad beskrivning 1}
            '',        {detaljerad beskrivning 2}
            '',        {detaljerad beskrivning 3}
            '',        {detaljerad beskrivning 4}
            '',        {detaljerad beskrivning 5}
            0,         {”ka strength}
            0,         {”ka defence}
            0);        {strength demanded to use object}


 Reset_Weapons3;

end;
end.
